export { default as '1C Enterprise' } from '../data/1C_20_Enterprise.js'
export { default as '2-Dimensional Array' } from '../data/2-Dimensional_20_Array.js'
export { default as '4D' } from '../data/4D.js'
export { default as 'ABAP' } from '../data/ABAP.js'
export { default as 'ABAP CDS' } from '../data/ABAP_20_CDS.js'
export { default as 'ABNF' } from '../data/ABNF.js'
export { default as 'AGS Script' } from '../data/AGS_20_Script.js'
export { default as 'AIDL' } from '../data/AIDL.js'
export { default as 'AL' } from '../data/AL.js'
export { default as 'AMPL' } from '../data/AMPL.js'
export { default as 'ANTLR' } from '../data/ANTLR.js'
export { default as 'API Blueprint' } from '../data/API_20_Blueprint.js'
export { default as 'APL' } from '../data/APL.js'
export { default as 'ASL' } from '../data/ASL.js'
export { default as 'ASN.1' } from '../data/ASN.1.js'
export { default as 'ASP.NET' } from '../data/ASP.NET.js'
export { default as 'ATS' } from '../data/ATS.js'
export { default as 'ActionScript' } from '../data/ActionScript.js'
export { default as 'Ada' } from '../data/Ada.js'
export { default as 'Adblock Filter List' } from '../data/Adblock_20_Filter_20_List.js'
export { default as 'Adobe Font Metrics' } from '../data/Adobe_20_Font_20_Metrics.js'
export { default as 'Agda' } from '../data/Agda.js'
export { default as 'Aiken' } from '../data/Aiken.js'
export { default as 'Alloy' } from '../data/Alloy.js'
export { default as 'Alpine Abuild' } from '../data/Alpine_20_Abuild.js'
export { default as 'Altium Designer' } from '../data/Altium_20_Designer.js'
export { default as 'AngelScript' } from '../data/AngelScript.js'
export { default as 'Answer Set Programming' } from '../data/Answer_20_Set_20_Programming.js'
export { default as 'Ant Build System' } from '../data/Ant_20_Build_20_System.js'
export { default as 'Antlers' } from '../data/Antlers.js'
export { default as 'ApacheConf' } from '../data/ApacheConf.js'
export { default as 'Apex' } from '../data/Apex.js'
export { default as 'Apollo Guidance Computer' } from '../data/Apollo_20_Guidance_20_Computer.js'
export { default as 'AppleScript' } from '../data/AppleScript.js'
export { default as 'Arc' } from '../data/Arc.js'
export { default as 'AsciiDoc' } from '../data/AsciiDoc.js'
export { default as 'AspectJ' } from '../data/AspectJ.js'
export { default as 'Assembly' } from '../data/Assembly.js'
export { default as 'Astro' } from '../data/Astro.js'
export { default as 'Asymptote' } from '../data/Asymptote.js'
export { default as 'Augeas' } from '../data/Augeas.js'
export { default as 'AutoHotkey' } from '../data/AutoHotkey.js'
export { default as 'AutoIt' } from '../data/AutoIt.js'
export { default as 'Avro IDL' } from '../data/Avro_20_IDL.js'
export { default as 'Awk' } from '../data/Awk.js'
export { default as 'B4X' } from '../data/B4X.js'
export { default as 'BASIC' } from '../data/BASIC.js'
export { default as 'BQN' } from '../data/BQN.js'
export { default as 'Ballerina' } from '../data/Ballerina.js'
export { default as 'Batchfile' } from '../data/Batchfile.js'
export { default as 'Beef' } from '../data/Beef.js'
export { default as 'Befunge' } from '../data/Befunge.js'
export { default as 'Berry' } from '../data/Berry.js'
export { default as 'BibTeX' } from '../data/BibTeX.js'
export { default as 'BibTeX Style' } from '../data/BibTeX_20_Style.js'
export { default as 'Bicep' } from '../data/Bicep.js'
export { default as 'Bikeshed' } from '../data/Bikeshed.js'
export { default as 'Bison' } from '../data/Bison.js'
export { default as 'BitBake' } from '../data/BitBake.js'
export { default as 'Blade' } from '../data/Blade.js'
export { default as 'BlitzBasic' } from '../data/BlitzBasic.js'
export { default as 'BlitzMax' } from '../data/BlitzMax.js'
export { default as 'Bluespec' } from '../data/Bluespec.js'
export { default as 'Bluespec BH' } from '../data/Bluespec_20_BH.js'
export { default as 'Boo' } from '../data/Boo.js'
export { default as 'Boogie' } from '../data/Boogie.js'
export { default as 'Brainfuck' } from '../data/Brainfuck.js'
export { default as 'BrighterScript' } from '../data/BrighterScript.js'
export { default as 'Brightscript' } from '../data/Brightscript.js'
export { default as 'Browserslist' } from '../data/Browserslist.js'
export { default as 'Bru' } from '../data/Bru.js'
export { default as 'BuildStream' } from '../data/BuildStream.js'
export { default as 'C' } from '../data/C.js'
export { default as 'C#' } from '../data/C_23_.js'
export { default as 'C++' } from '../data/C_2b__2b_.js'
export { default as 'C-ObjDump' } from '../data/C-ObjDump.js'
export { default as 'C2hs Haskell' } from '../data/C2hs_20_Haskell.js'
export { default as 'C3' } from '../data/C3.js'
export { default as 'CAP CDS' } from '../data/CAP_20_CDS.js'
export { default as 'CIL' } from '../data/CIL.js'
export { default as 'CLIPS' } from '../data/CLIPS.js'
export { default as 'CMake' } from '../data/CMake.js'
export { default as 'COBOL' } from '../data/COBOL.js'
export { default as 'CODEOWNERS' } from '../data/CODEOWNERS.js'
export { default as 'COLLADA' } from '../data/COLLADA.js'
export { default as 'CSON' } from '../data/CSON.js'
export { default as 'CSS' } from '../data/CSS.js'
export { default as 'CSV' } from '../data/CSV.js'
export { default as 'CUE' } from '../data/CUE.js'
export { default as 'CWeb' } from '../data/CWeb.js'
export { default as 'Cabal Config' } from '../data/Cabal_20_Config.js'
export { default as 'Caddyfile' } from '../data/Caddyfile.js'
export { default as 'Cadence' } from '../data/Cadence.js'
export { default as 'Cairo' } from '../data/Cairo.js'
export { default as 'Cairo Zero' } from '../data/Cairo_20_Zero.js'
export { default as 'CameLIGO' } from '../data/CameLIGO.js'
export { default as "Cap'n Proto" } from '../data/Cap_27_n_20_Proto.js'
export { default as 'Carbon' } from '../data/Carbon.js'
export { default as 'CartoCSS' } from '../data/CartoCSS.js'
export { default as 'Ceylon' } from '../data/Ceylon.js'
export { default as 'Chapel' } from '../data/Chapel.js'
export { default as 'Charity' } from '../data/Charity.js'
export { default as 'Checksums' } from '../data/Checksums.js'
export { default as 'ChucK' } from '../data/ChucK.js'
export { default as 'Circom' } from '../data/Circom.js'
export { default as 'Cirru' } from '../data/Cirru.js'
export { default as 'Clarion' } from '../data/Clarion.js'
export { default as 'Clarity' } from '../data/Clarity.js'
export { default as 'Classic ASP' } from '../data/Classic_20_ASP.js'
export { default as 'Clean' } from '../data/Clean.js'
export { default as 'Click' } from '../data/Click.js'
export { default as 'Clojure' } from '../data/Clojure.js'
export { default as 'Closure Templates' } from '../data/Closure_20_Templates.js'
export { default as 'Cloud Firestore Security Rules' } from '../data/Cloud_20_Firestore_20_Security_20_Rules.js'
export { default as 'Clue' } from '../data/Clue.js'
export { default as 'CoNLL-U' } from '../data/CoNLL-U.js'
export { default as 'CodeQL' } from '../data/CodeQL.js'
export { default as 'CoffeeScript' } from '../data/CoffeeScript.js'
export { default as 'ColdFusion' } from '../data/ColdFusion.js'
export { default as 'ColdFusion CFC' } from '../data/ColdFusion_20_CFC.js'
export { default as 'Common Lisp' } from '../data/Common_20_Lisp.js'
export { default as 'Common Workflow Language' } from '../data/Common_20_Workflow_20_Language.js'
export { default as 'Component Pascal' } from '../data/Component_20_Pascal.js'
export { default as 'Cooklang' } from '../data/Cooklang.js'
export { default as 'Cool' } from '../data/Cool.js'
export { default as 'Cpp-ObjDump' } from '../data/Cpp-ObjDump.js'
export { default as 'Creole' } from '../data/Creole.js'
export { default as 'Crystal' } from '../data/Crystal.js'
export { default as 'Csound' } from '../data/Csound.js'
export { default as 'Csound Document' } from '../data/Csound_20_Document.js'
export { default as 'Csound Score' } from '../data/Csound_20_Score.js'
export { default as 'Cuda' } from '../data/Cuda.js'
export { default as 'Cue Sheet' } from '../data/Cue_20_Sheet.js'
export { default as 'Curry' } from '../data/Curry.js'
export { default as 'Cycript' } from '../data/Cycript.js'
export { default as 'Cylc' } from '../data/Cylc.js'
export { default as 'Cypher' } from '../data/Cypher.js'
export { default as 'Cython' } from '../data/Cython.js'
export { default as 'D' } from '../data/D.js'
export { default as 'D-ObjDump' } from '../data/D-ObjDump.js'
export { default as 'D2' } from '../data/D2.js'
export { default as 'DIGITAL Command Language' } from '../data/DIGITAL_20_Command_20_Language.js'
export { default as 'DM' } from '../data/DM.js'
export { default as 'DNS Zone' } from '../data/DNS_20_Zone.js'
export { default as 'DTrace' } from '../data/DTrace.js'
export { default as 'Dafny' } from '../data/Dafny.js'
export { default as 'Darcs Patch' } from '../data/Darcs_20_Patch.js'
export { default as 'Dart' } from '../data/Dart.js'
export { default as 'Daslang' } from '../data/Daslang.js'
export { default as 'DataWeave' } from '../data/DataWeave.js'
export { default as 'Debian Package Control File' } from '../data/Debian_20_Package_20_Control_20_File.js'
export { default as 'DenizenScript' } from '../data/DenizenScript.js'
export { default as 'Dhall' } from '../data/Dhall.js'
export { default as 'Diff' } from '../data/Diff.js'
export { default as 'DirectX 3D File' } from '../data/DirectX_20_3D_20_File.js'
export { default as 'Dockerfile' } from '../data/Dockerfile.js'
export { default as 'Dogescript' } from '../data/Dogescript.js'
export { default as 'Dotenv' } from '../data/Dotenv.js'
export { default as 'Dune' } from '../data/Dune.js'
export { default as 'Dylan' } from '../data/Dylan.js'
export { default as 'E' } from '../data/E.js'
export { default as 'E-mail' } from '../data/E-mail.js'
export { default as 'EBNF' } from '../data/EBNF.js'
export { default as 'ECL' } from '../data/ECL.js'
export { default as 'ECLiPSe' } from '../data/ECLiPSe.js'
export { default as 'EJS' } from '../data/EJS.js'
export { default as 'EQ' } from '../data/EQ.js'
export { default as 'Eagle' } from '../data/Eagle.js'
export { default as 'Earthly' } from '../data/Earthly.js'
export { default as 'Easybuild' } from '../data/Easybuild.js'
export { default as 'Ecere Projects' } from '../data/Ecere_20_Projects.js'
export { default as 'Ecmarkup' } from '../data/Ecmarkup.js'
export { default as 'Edge' } from '../data/Edge.js'
export { default as 'EdgeQL' } from '../data/EdgeQL.js'
export { default as 'EditorConfig' } from '../data/EditorConfig.js'
export { default as 'Edje Data Collection' } from '../data/Edje_20_Data_20_Collection.js'
export { default as 'Eiffel' } from '../data/Eiffel.js'
export { default as 'Elixir' } from '../data/Elixir.js'
export { default as 'Elm' } from '../data/Elm.js'
export { default as 'Elvish' } from '../data/Elvish.js'
export { default as 'Elvish Transcript' } from '../data/Elvish_20_Transcript.js'
export { default as 'Emacs Lisp' } from '../data/Emacs_20_Lisp.js'
export { default as 'EmberScript' } from '../data/EmberScript.js'
export { default as 'Erlang' } from '../data/Erlang.js'
export { default as 'Euphoria' } from '../data/Euphoria.js'
export { default as 'F#' } from '../data/F_23_.js'
export { default as 'F*' } from '../data/F_2a_.js'
export { default as 'FIGlet Font' } from '../data/FIGlet_20_Font.js'
export { default as 'FIRRTL' } from '../data/FIRRTL.js'
export { default as 'FLUX' } from '../data/FLUX.js'
export { default as 'Factor' } from '../data/Factor.js'
export { default as 'Fancy' } from '../data/Fancy.js'
export { default as 'Fantom' } from '../data/Fantom.js'
export { default as 'Faust' } from '../data/Faust.js'
export { default as 'Fennel' } from '../data/Fennel.js'
export { default as 'Filebench WML' } from '../data/Filebench_20_WML.js'
export { default as 'Filterscript' } from '../data/Filterscript.js'
export { default as 'Flix' } from '../data/Flix.js'
export { default as 'Fluent' } from '../data/Fluent.js'
export { default as 'Formatted' } from '../data/Formatted.js'
export { default as 'Forth' } from '../data/Forth.js'
export { default as 'Fortran' } from '../data/Fortran.js'
export { default as 'Fortran Free Form' } from '../data/Fortran_20_Free_20_Form.js'
export { default as 'FreeBASIC' } from '../data/FreeBASIC.js'
export { default as 'FreeMarker' } from '../data/FreeMarker.js'
export { default as 'Frege' } from '../data/Frege.js'
export { default as 'Futhark' } from '../data/Futhark.js'
export { default as 'G-code' } from '../data/G-code.js'
export { default as 'GAML' } from '../data/GAML.js'
export { default as 'GAMS' } from '../data/GAMS.js'
export { default as 'GAP' } from '../data/GAP.js'
export { default as 'GCC Machine Description' } from '../data/GCC_20_Machine_20_Description.js'
export { default as 'GDB' } from '../data/GDB.js'
export { default as 'GDScript' } from '../data/GDScript.js'
export { default as 'GDShader' } from '../data/GDShader.js'
export { default as 'GEDCOM' } from '../data/GEDCOM.js'
export { default as 'GLSL' } from '../data/GLSL.js'
export { default as 'GN' } from '../data/GN.js'
export { default as 'GSC' } from '../data/GSC.js'
export { default as 'Game Maker Language' } from '../data/Game_20_Maker_20_Language.js'
export { default as 'Gemfile.lock' } from '../data/Gemfile.lock.js'
export { default as 'Gemini' } from '../data/Gemini.js'
export { default as 'Genero 4gl' } from '../data/Genero_20_4gl.js'
export { default as 'Genero per' } from '../data/Genero_20_per.js'
export { default as 'Genie' } from '../data/Genie.js'
export { default as 'Genshi' } from '../data/Genshi.js'
export { default as 'Gentoo Ebuild' } from '../data/Gentoo_20_Ebuild.js'
export { default as 'Gentoo Eclass' } from '../data/Gentoo_20_Eclass.js'
export { default as 'Gerber Image' } from '../data/Gerber_20_Image.js'
export { default as 'Gettext Catalog' } from '../data/Gettext_20_Catalog.js'
export { default as 'Gherkin' } from '../data/Gherkin.js'
export { default as 'Git Attributes' } from '../data/Git_20_Attributes.js'
export { default as 'Git Config' } from '../data/Git_20_Config.js'
export { default as 'Git Revision List' } from '../data/Git_20_Revision_20_List.js'
export { default as 'Gleam' } from '../data/Gleam.js'
export { default as 'Glimmer JS' } from '../data/Glimmer_20_JS.js'
export { default as 'Glimmer TS' } from '../data/Glimmer_20_TS.js'
export { default as 'Glyph' } from '../data/Glyph.js'
export { default as 'Glyph Bitmap Distribution Format' } from '../data/Glyph_20_Bitmap_20_Distribution_20_Format.js'
export { default as 'Gnuplot' } from '../data/Gnuplot.js'
export { default as 'Go' } from '../data/Go.js'
export { default as 'Go Checksums' } from '../data/Go_20_Checksums.js'
export { default as 'Go Module' } from '../data/Go_20_Module.js'
export { default as 'Go Workspace' } from '../data/Go_20_Workspace.js'
export { default as 'Godot Resource' } from '../data/Godot_20_Resource.js'
export { default as 'Golo' } from '../data/Golo.js'
export { default as 'Gosu' } from '../data/Gosu.js'
export { default as 'Grace' } from '../data/Grace.js'
export { default as 'Gradle' } from '../data/Gradle.js'
export { default as 'Gradle Kotlin DSL' } from '../data/Gradle_20_Kotlin_20_DSL.js'
export { default as 'Grammatical Framework' } from '../data/Grammatical_20_Framework.js'
export { default as 'Graph Modeling Language' } from '../data/Graph_20_Modeling_20_Language.js'
export { default as 'GraphQL' } from '../data/GraphQL.js'
export { default as 'Graphviz (DOT)' } from '../data/Graphviz_20__28_DOT_29_.js'
export { default as 'Groovy' } from '../data/Groovy.js'
export { default as 'Groovy Server Pages' } from '../data/Groovy_20_Server_20_Pages.js'
export { default as 'HAProxy' } from '../data/HAProxy.js'
export { default as 'HCL' } from '../data/HCL.js'
export { default as 'HIP' } from '../data/HIP.js'
export { default as 'HLSL' } from '../data/HLSL.js'
export { default as 'HOCON' } from '../data/HOCON.js'
export { default as 'HTML' } from '../data/HTML.js'
export { default as 'HTML+ECR' } from '../data/HTML_2b_ECR.js'
export { default as 'HTML+EEX' } from '../data/HTML_2b_EEX.js'
export { default as 'HTML+ERB' } from '../data/HTML_2b_ERB.js'
export { default as 'HTML+PHP' } from '../data/HTML_2b_PHP.js'
export { default as 'HTML+Razor' } from '../data/HTML_2b_Razor.js'
export { default as 'HTTP' } from '../data/HTTP.js'
export { default as 'HXML' } from '../data/HXML.js'
export { default as 'Hack' } from '../data/Hack.js'
export { default as 'Haml' } from '../data/Haml.js'
export { default as 'Handlebars' } from '../data/Handlebars.js'
export { default as 'Harbour' } from '../data/Harbour.js'
export { default as 'Hare' } from '../data/Hare.js'
export { default as 'Haskell' } from '../data/Haskell.js'
export { default as 'Haxe' } from '../data/Haxe.js'
export { default as 'HiveQL' } from '../data/HiveQL.js'
export { default as 'HolyC' } from '../data/HolyC.js'
export { default as 'Hosts File' } from '../data/Hosts_20_File.js'
export { default as 'Hy' } from '../data/Hy.js'
export { default as 'HyPhy' } from '../data/HyPhy.js'
export { default as 'IDL' } from '../data/IDL.js'
export { default as 'IGOR Pro' } from '../data/IGOR_20_Pro.js'
export { default as 'INI' } from '../data/INI.js'
export { default as 'IRC log' } from '../data/IRC_20_log.js'
export { default as 'ISPC' } from '../data/ISPC.js'
export { default as 'Idris' } from '../data/Idris.js'
export { default as 'Ignore List' } from '../data/Ignore_20_List.js'
export { default as 'ImageJ Macro' } from '../data/ImageJ_20_Macro.js'
export { default as 'Imba' } from '../data/Imba.js'
export { default as 'Inform 7' } from '../data/Inform_20_7.js'
export { default as 'Ink' } from '../data/Ink.js'
export { default as 'Inno Setup' } from '../data/Inno_20_Setup.js'
export { default as 'Io' } from '../data/Io.js'
export { default as 'Ioke' } from '../data/Ioke.js'
export { default as 'Isabelle' } from '../data/Isabelle.js'
export { default as 'Isabelle ROOT' } from '../data/Isabelle_20_ROOT.js'
export { default as 'J' } from '../data/J.js'
export { default as 'JAR Manifest' } from '../data/JAR_20_Manifest.js'
export { default as 'JCL' } from '../data/JCL.js'
export { default as 'JFlex' } from '../data/JFlex.js'
export { default as 'JSON' } from '../data/JSON.js'
export { default as 'JSON with Comments' } from '../data/JSON_20_with_20_Comments.js'
export { default as 'JSON5' } from '../data/JSON5.js'
export { default as 'JSONLD' } from '../data/JSONLD.js'
export { default as 'JSONiq' } from '../data/JSONiq.js'
export { default as 'Jai' } from '../data/Jai.js'
export { default as 'Janet' } from '../data/Janet.js'
export { default as 'Jasmin' } from '../data/Jasmin.js'
export { default as 'Java' } from '../data/Java.js'
export { default as 'Java Properties' } from '../data/Java_20_Properties.js'
export { default as 'Java Server Pages' } from '../data/Java_20_Server_20_Pages.js'
export { default as 'Java Template Engine' } from '../data/Java_20_Template_20_Engine.js'
export { default as 'JavaScript' } from '../data/JavaScript.js'
export { default as 'JavaScript+ERB' } from '../data/JavaScript_2b_ERB.js'
export { default as 'Jest Snapshot' } from '../data/Jest_20_Snapshot.js'
export { default as 'JetBrains MPS' } from '../data/JetBrains_20_MPS.js'
export { default as 'Jinja' } from '../data/Jinja.js'
export { default as 'Jison' } from '../data/Jison.js'
export { default as 'Jison Lex' } from '../data/Jison_20_Lex.js'
export { default as 'Jolie' } from '../data/Jolie.js'
export { default as 'Jsonnet' } from '../data/Jsonnet.js'
export { default as 'Julia' } from '../data/Julia.js'
export { default as 'Julia REPL' } from '../data/Julia_20_REPL.js'
export { default as 'Jupyter Notebook' } from '../data/Jupyter_20_Notebook.js'
export { default as 'Just' } from '../data/Just.js'
export { default as 'KDL' } from '../data/KDL.js'
export { default as 'KRL' } from '../data/KRL.js'
export { default as 'Kaitai Struct' } from '../data/Kaitai_20_Struct.js'
export { default as 'KakouneScript' } from '../data/KakouneScript.js'
export { default as 'KerboScript' } from '../data/KerboScript.js'
export { default as 'KiCad Layout' } from '../data/KiCad_20_Layout.js'
export { default as 'KiCad Legacy Layout' } from '../data/KiCad_20_Legacy_20_Layout.js'
export { default as 'KiCad Schematic' } from '../data/KiCad_20_Schematic.js'
export { default as 'Kickstart' } from '../data/Kickstart.js'
export { default as 'Kit' } from '../data/Kit.js'
export { default as 'KoLMafia ASH' } from '../data/KoLMafia_20_ASH.js'
export { default as 'Koka' } from '../data/Koka.js'
export { default as 'Kotlin' } from '../data/Kotlin.js'
export { default as 'Kusto' } from '../data/Kusto.js'
export { default as 'LFE' } from '../data/LFE.js'
export { default as 'LLVM' } from '../data/LLVM.js'
export { default as 'LOLCODE' } from '../data/LOLCODE.js'
export { default as 'LSL' } from '../data/LSL.js'
export { default as 'LTspice Symbol' } from '../data/LTspice_20_Symbol.js'
export { default as 'LabVIEW' } from '../data/LabVIEW.js'
export { default as 'Lark' } from '../data/Lark.js'
export { default as 'Lasso' } from '../data/Lasso.js'
export { default as 'Latte' } from '../data/Latte.js'
export { default as 'Lean' } from '../data/Lean.js'
export { default as 'Lean 4' } from '../data/Lean_20_4.js'
export { default as 'Leo' } from '../data/Leo.js'
export { default as 'Less' } from '../data/Less.js'
export { default as 'Lex' } from '../data/Lex.js'
export { default as 'LigoLANG' } from '../data/LigoLANG.js'
export { default as 'LilyPond' } from '../data/LilyPond.js'
export { default as 'Limbo' } from '../data/Limbo.js'
export { default as 'Linear Programming' } from '../data/Linear_20_Programming.js'
export { default as 'Linker Script' } from '../data/Linker_20_Script.js'
export { default as 'Linux Kernel Module' } from '../data/Linux_20_Kernel_20_Module.js'
export { default as 'Liquid' } from '../data/Liquid.js'
export { default as 'Literate Agda' } from '../data/Literate_20_Agda.js'
export { default as 'Literate CoffeeScript' } from '../data/Literate_20_CoffeeScript.js'
export { default as 'Literate Haskell' } from '../data/Literate_20_Haskell.js'
export { default as 'LiveCode Script' } from '../data/LiveCode_20_Script.js'
export { default as 'LiveScript' } from '../data/LiveScript.js'
export { default as 'Logos' } from '../data/Logos.js'
export { default as 'Logtalk' } from '../data/Logtalk.js'
export { default as 'LookML' } from '../data/LookML.js'
export { default as 'LoomScript' } from '../data/LoomScript.js'
export { default as 'Lua' } from '../data/Lua.js'
export { default as 'Luau' } from '../data/Luau.js'
export { default as 'M' } from '../data/M.js'
export { default as 'M3U' } from '../data/M3U.js'
export { default as 'M4' } from '../data/M4.js'
export { default as 'M4Sugar' } from '../data/M4Sugar.js'
export { default as 'MATLAB' } from '../data/MATLAB.js'
export { default as 'MAXScript' } from '../data/MAXScript.js'
export { default as 'MDX' } from '../data/MDX.js'
export { default as 'MLIR' } from '../data/MLIR.js'
export { default as 'MQL4' } from '../data/MQL4.js'
export { default as 'MQL5' } from '../data/MQL5.js'
export { default as 'MTML' } from '../data/MTML.js'
export { default as 'MUF' } from '../data/MUF.js'
export { default as 'Macaulay2' } from '../data/Macaulay2.js'
export { default as 'Makefile' } from '../data/Makefile.js'
export { default as 'Mako' } from '../data/Mako.js'
export { default as 'Markdown' } from '../data/Markdown.js'
export { default as 'Marko' } from '../data/Marko.js'
export { default as 'Mask' } from '../data/Mask.js'
export { default as 'Mathematica' } from '../data/Mathematica.js'
export { default as 'Maven POM' } from '../data/Maven_20_POM.js'
export { default as 'Max' } from '../data/Max.js'
export { default as 'Mercury' } from '../data/Mercury.js'
export { default as 'Mermaid' } from '../data/Mermaid.js'
export { default as 'Meson' } from '../data/Meson.js'
export { default as 'Metal' } from '../data/Metal.js'
export { default as 'Microsoft Developer Studio Project' } from '../data/Microsoft_20_Developer_20_Studio_20_Project.js'
export { default as 'Microsoft Visual Studio Solution' } from '../data/Microsoft_20_Visual_20_Studio_20_Solution.js'
export { default as 'MiniD' } from '../data/MiniD.js'
export { default as 'MiniYAML' } from '../data/MiniYAML.js'
export { default as 'MiniZinc' } from '../data/MiniZinc.js'
export { default as 'MiniZinc Data' } from '../data/MiniZinc_20_Data.js'
export { default as 'Mint' } from '../data/Mint.js'
export { default as 'Mirah' } from '../data/Mirah.js'
export { default as 'Modelica' } from '../data/Modelica.js'
export { default as 'Modula-2' } from '../data/Modula-2.js'
export { default as 'Modula-3' } from '../data/Modula-3.js'
export { default as 'Module Management System' } from '../data/Module_20_Management_20_System.js'
export { default as 'Mojo' } from '../data/Mojo.js'
export { default as 'Monkey' } from '../data/Monkey.js'
export { default as 'Monkey C' } from '../data/Monkey_20_C.js'
export { default as 'Moocode' } from '../data/Moocode.js'
export { default as 'MoonBit' } from '../data/MoonBit.js'
export { default as 'MoonScript' } from '../data/MoonScript.js'
export { default as 'Motoko' } from '../data/Motoko.js'
export { default as 'Motorola 68K Assembly' } from '../data/Motorola_20_68K_20_Assembly.js'
export { default as 'Move' } from '../data/Move.js'
export { default as 'Muse' } from '../data/Muse.js'
export { default as 'Mustache' } from '../data/Mustache.js'
export { default as 'Myghty' } from '../data/Myghty.js'
export { default as 'NASL' } from '../data/NASL.js'
export { default as 'NCL' } from '../data/NCL.js'
export { default as 'NEON' } from '../data/NEON.js'
export { default as 'NL' } from '../data/NL.js'
export { default as 'NMODL' } from '../data/NMODL.js'
export { default as 'NPM Config' } from '../data/NPM_20_Config.js'
export { default as 'NSIS' } from '../data/NSIS.js'
export { default as 'NWScript' } from '../data/NWScript.js'
export { default as 'Nasal' } from '../data/Nasal.js'
export { default as 'Nearley' } from '../data/Nearley.js'
export { default as 'Nemerle' } from '../data/Nemerle.js'
export { default as 'NetLinx' } from '../data/NetLinx.js'
export { default as 'NetLinx+ERB' } from '../data/NetLinx_2b_ERB.js'
export { default as 'NetLogo' } from '../data/NetLogo.js'
export { default as 'NewLisp' } from '../data/NewLisp.js'
export { default as 'Nextflow' } from '../data/Nextflow.js'
export { default as 'Nginx' } from '../data/Nginx.js'
export { default as 'Nickel' } from '../data/Nickel.js'
export { default as 'Nim' } from '../data/Nim.js'
export { default as 'Ninja' } from '../data/Ninja.js'
export { default as 'Nit' } from '../data/Nit.js'
export { default as 'Nix' } from '../data/Nix.js'
export { default as 'Noir' } from '../data/Noir.js'
export { default as 'Nu' } from '../data/Nu.js'
export { default as 'NumPy' } from '../data/NumPy.js'
export { default as 'Nunjucks' } from '../data/Nunjucks.js'
export { default as 'Nushell' } from '../data/Nushell.js'
export { default as 'OASv2-json' } from '../data/OASv2-json.js'
export { default as 'OASv2-yaml' } from '../data/OASv2-yaml.js'
export { default as 'OASv3-json' } from '../data/OASv3-json.js'
export { default as 'OASv3-yaml' } from '../data/OASv3-yaml.js'
export { default as 'OCaml' } from '../data/OCaml.js'
export { default as 'OMNeT++ MSG' } from '../data/OMNeT_2b__2b__20_MSG.js'
export { default as 'OMNeT++ NED' } from '../data/OMNeT_2b__2b__20_NED.js'
export { default as 'Oberon' } from '../data/Oberon.js'
export { default as 'ObjDump' } from '../data/ObjDump.js'
export { default as 'Object Data Instance Notation' } from '../data/Object_20_Data_20_Instance_20_Notation.js'
export { default as 'ObjectScript' } from '../data/ObjectScript.js'
export { default as 'Objective-C' } from '../data/Objective-C.js'
export { default as 'Objective-C++' } from '../data/Objective-C_2b__2b_.js'
export { default as 'Objective-J' } from '../data/Objective-J.js'
export { default as 'Odin' } from '../data/Odin.js'
export { default as 'Omgrofl' } from '../data/Omgrofl.js'
export { default as 'Opa' } from '../data/Opa.js'
export { default as 'Opal' } from '../data/Opal.js'
export { default as 'Open Policy Agent' } from '../data/Open_20_Policy_20_Agent.js'
export { default as 'OpenAPI Specification v2' } from '../data/OpenAPI_20_Specification_20_v2.js'
export { default as 'OpenAPI Specification v3' } from '../data/OpenAPI_20_Specification_20_v3.js'
export { default as 'OpenCL' } from '../data/OpenCL.js'
export { default as 'OpenEdge ABL' } from '../data/OpenEdge_20_ABL.js'
export { default as 'OpenQASM' } from '../data/OpenQASM.js'
export { default as 'OpenRC runscript' } from '../data/OpenRC_20_runscript.js'
export { default as 'OpenSCAD' } from '../data/OpenSCAD.js'
export { default as 'OpenStep Property List' } from '../data/OpenStep_20_Property_20_List.js'
export { default as 'OpenType Feature File' } from '../data/OpenType_20_Feature_20_File.js'
export { default as 'Option List' } from '../data/Option_20_List.js'
export { default as 'Org' } from '../data/Org.js'
export { default as 'OverpassQL' } from '../data/OverpassQL.js'
export { default as 'Ox' } from '../data/Ox.js'
export { default as 'Oxygene' } from '../data/Oxygene.js'
export { default as 'Oz' } from '../data/Oz.js'
export { default as 'P4' } from '../data/P4.js'
export { default as 'PDDL' } from '../data/PDDL.js'
export { default as 'PEG.js' } from '../data/PEG.js.js'
export { default as 'PHP' } from '../data/PHP.js'
export { default as 'PLSQL' } from '../data/PLSQL.js'
export { default as 'PLpgSQL' } from '../data/PLpgSQL.js'
export { default as 'POV-Ray SDL' } from '../data/POV-Ray_20_SDL.js'
export { default as 'Pact' } from '../data/Pact.js'
export { default as 'Pan' } from '../data/Pan.js'
export { default as 'Papyrus' } from '../data/Papyrus.js'
export { default as 'Parrot' } from '../data/Parrot.js'
export { default as 'Parrot Assembly' } from '../data/Parrot_20_Assembly.js'
export { default as 'Parrot Internal Representation' } from '../data/Parrot_20_Internal_20_Representation.js'
export { default as 'Pascal' } from '../data/Pascal.js'
export { default as 'Pawn' } from '../data/Pawn.js'
export { default as 'Pep8' } from '../data/Pep8.js'
export { default as 'Perl' } from '../data/Perl.js'
export { default as 'Pic' } from '../data/Pic.js'
export { default as 'Pickle' } from '../data/Pickle.js'
export { default as 'PicoLisp' } from '../data/PicoLisp.js'
export { default as 'PigLatin' } from '../data/PigLatin.js'
export { default as 'Pike' } from '../data/Pike.js'
export { default as 'Pip Requirements' } from '../data/Pip_20_Requirements.js'
export { default as 'Pkl' } from '../data/Pkl.js'
export { default as 'PlantUML' } from '../data/PlantUML.js'
export { default as 'Pod' } from '../data/Pod.js'
export { default as 'Pod 6' } from '../data/Pod_20_6.js'
export { default as 'PogoScript' } from '../data/PogoScript.js'
export { default as 'Polar' } from '../data/Polar.js'
export { default as 'Pony' } from '../data/Pony.js'
export { default as 'Portugol' } from '../data/Portugol.js'
export { default as 'PostCSS' } from '../data/PostCSS.js'
export { default as 'PostScript' } from '../data/PostScript.js'
export { default as 'PowerBuilder' } from '../data/PowerBuilder.js'
export { default as 'PowerShell' } from '../data/PowerShell.js'
export { default as 'Praat' } from '../data/Praat.js'
export { default as 'Prisma' } from '../data/Prisma.js'
export { default as 'Processing' } from '../data/Processing.js'
export { default as 'Procfile' } from '../data/Procfile.js'
export { default as 'Proguard' } from '../data/Proguard.js'
export { default as 'Prolog' } from '../data/Prolog.js'
export { default as 'Promela' } from '../data/Promela.js'
export { default as 'Propeller Spin' } from '../data/Propeller_20_Spin.js'
export { default as 'Protocol Buffer' } from '../data/Protocol_20_Buffer.js'
export { default as 'Protocol Buffer Text Format' } from '../data/Protocol_20_Buffer_20_Text_20_Format.js'
export { default as 'Public Key' } from '../data/Public_20_Key.js'
export { default as 'Pug' } from '../data/Pug.js'
export { default as 'Puppet' } from '../data/Puppet.js'
export { default as 'Pure Data' } from '../data/Pure_20_Data.js'
export { default as 'PureBasic' } from '../data/PureBasic.js'
export { default as 'PureScript' } from '../data/PureScript.js'
export { default as 'Pyret' } from '../data/Pyret.js'
export { default as 'Python' } from '../data/Python.js'
export { default as 'Python console' } from '../data/Python_20_console.js'
export { default as 'Python traceback' } from '../data/Python_20_traceback.js'
export { default as 'Q#' } from '../data/Q_23_.js'
export { default as 'QML' } from '../data/QML.js'
export { default as 'QMake' } from '../data/QMake.js'
export { default as 'Qt Script' } from '../data/Qt_20_Script.js'
export { default as 'Quake' } from '../data/Quake.js'
export { default as 'QuakeC' } from '../data/QuakeC.js'
export { default as 'QuickBASIC' } from '../data/QuickBASIC.js'
export { default as 'R' } from '../data/R.js'
export { default as 'RAML' } from '../data/RAML.js'
export { default as 'RBS' } from '../data/RBS.js'
export { default as 'RDoc' } from '../data/RDoc.js'
export { default as 'REALbasic' } from '../data/REALbasic.js'
export { default as 'REXX' } from '../data/REXX.js'
export { default as 'RMarkdown' } from '../data/RMarkdown.js'
export { default as 'RON' } from '../data/RON.js'
export { default as 'ROS Interface' } from '../data/ROS_20_Interface.js'
export { default as 'RPC' } from '../data/RPC.js'
export { default as 'RPGLE' } from '../data/RPGLE.js'
export { default as 'RPM Spec' } from '../data/RPM_20_Spec.js'
export { default as 'RUNOFF' } from '../data/RUNOFF.js'
export { default as 'Racket' } from '../data/Racket.js'
export { default as 'Ragel' } from '../data/Ragel.js'
export { default as 'Raku' } from '../data/Raku.js'
export { default as 'Rascal' } from '../data/Rascal.js'
export { default as 'Raw token data' } from '../data/Raw_20_token_20_data.js'
export { default as 'ReScript' } from '../data/ReScript.js'
export { default as 'Readline Config' } from '../data/Readline_20_Config.js'
export { default as 'Reason' } from '../data/Reason.js'
export { default as 'ReasonLIGO' } from '../data/ReasonLIGO.js'
export { default as 'Rebol' } from '../data/Rebol.js'
export { default as 'Record Jar' } from '../data/Record_20_Jar.js'
export { default as 'Red' } from '../data/Red.js'
export { default as 'Redcode' } from '../data/Redcode.js'
export { default as 'Redirect Rules' } from '../data/Redirect_20_Rules.js'
export { default as 'Regular Expression' } from '../data/Regular_20_Expression.js'
export { default as "Ren'Py" } from '../data/Ren_27_Py.js'
export { default as 'RenderScript' } from '../data/RenderScript.js'
export { default as 'Rez' } from '../data/Rez.js'
export { default as 'Rich Text Format' } from '../data/Rich_20_Text_20_Format.js'
export { default as 'Ring' } from '../data/Ring.js'
export { default as 'Riot' } from '../data/Riot.js'
export { default as 'RobotFramework' } from '../data/RobotFramework.js'
export { default as 'Roc' } from '../data/Roc.js'
export { default as 'Rocq Prover' } from '../data/Rocq_20_Prover.js'
export { default as 'Roff' } from '../data/Roff.js'
export { default as 'Roff Manpage' } from '../data/Roff_20_Manpage.js'
export { default as 'Rouge' } from '../data/Rouge.js'
export { default as 'RouterOS Script' } from '../data/RouterOS_20_Script.js'
export { default as 'Ruby' } from '../data/Ruby.js'
export { default as 'Rust' } from '../data/Rust.js'
export { default as 'SAS' } from '../data/SAS.js'
export { default as 'SCSS' } from '../data/SCSS.js'
export { default as 'SELinux Policy' } from '../data/SELinux_20_Policy.js'
export { default as 'SMT' } from '../data/SMT.js'
export { default as 'SPARQL' } from '../data/SPARQL.js'
export { default as 'SQF' } from '../data/SQF.js'
export { default as 'SQL' } from '../data/SQL.js'
export { default as 'SQLPL' } from '../data/SQLPL.js'
export { default as 'SRecode Template' } from '../data/SRecode_20_Template.js'
export { default as 'SSH Config' } from '../data/SSH_20_Config.js'
export { default as 'STAR' } from '../data/STAR.js'
export { default as 'STL' } from '../data/STL.js'
export { default as 'STON' } from '../data/STON.js'
export { default as 'SVG' } from '../data/SVG.js'
export { default as 'SWIG' } from '../data/SWIG.js'
export { default as 'Sage' } from '../data/Sage.js'
export { default as 'Sail' } from '../data/Sail.js'
export { default as 'SaltStack' } from '../data/SaltStack.js'
export { default as 'Sass' } from '../data/Sass.js'
export { default as 'Scala' } from '../data/Scala.js'
export { default as 'Scaml' } from '../data/Scaml.js'
export { default as 'Scenic' } from '../data/Scenic.js'
export { default as 'Scheme' } from '../data/Scheme.js'
export { default as 'Scilab' } from '../data/Scilab.js'
export { default as 'Self' } from '../data/Self.js'
export { default as 'ShaderLab' } from '../data/ShaderLab.js'
export { default as 'Shell' } from '../data/Shell.js'
export { default as 'ShellCheck Config' } from '../data/ShellCheck_20_Config.js'
export { default as 'ShellSession' } from '../data/ShellSession.js'
export { default as 'Shen' } from '../data/Shen.js'
export { default as 'Sieve' } from '../data/Sieve.js'
export { default as 'Simple File Verification' } from '../data/Simple_20_File_20_Verification.js'
export { default as 'Singularity' } from '../data/Singularity.js'
export { default as 'Slang' } from '../data/Slang.js'
export { default as 'Slash' } from '../data/Slash.js'
export { default as 'Slice' } from '../data/Slice.js'
export { default as 'Slim' } from '../data/Slim.js'
export { default as 'Slint' } from '../data/Slint.js'
export { default as 'SmPL' } from '../data/SmPL.js'
export { default as 'Smali' } from '../data/Smali.js'
export { default as 'Smalltalk' } from '../data/Smalltalk.js'
export { default as 'Smarty' } from '../data/Smarty.js'
export { default as 'Smithy' } from '../data/Smithy.js'
export { default as 'Snakemake' } from '../data/Snakemake.js'
export { default as 'Solidity' } from '../data/Solidity.js'
export { default as 'Soong' } from '../data/Soong.js'
export { default as 'SourcePawn' } from '../data/SourcePawn.js'
export { default as 'Spline Font Database' } from '../data/Spline_20_Font_20_Database.js'
export { default as 'Squirrel' } from '../data/Squirrel.js'
export { default as 'Stan' } from '../data/Stan.js'
export { default as 'Standard ML' } from '../data/Standard_20_ML.js'
export { default as 'Starlark' } from '../data/Starlark.js'
export { default as 'Stata' } from '../data/Stata.js'
export { default as 'StringTemplate' } from '../data/StringTemplate.js'
export { default as 'Stylus' } from '../data/Stylus.js'
export { default as 'SubRip Text' } from '../data/SubRip_20_Text.js'
export { default as 'SugarSS' } from '../data/SugarSS.js'
export { default as 'SuperCollider' } from '../data/SuperCollider.js'
export { default as 'Survex data' } from '../data/Survex_20_data.js'
export { default as 'Svelte' } from '../data/Svelte.js'
export { default as 'Sway' } from '../data/Sway.js'
export { default as 'Sweave' } from '../data/Sweave.js'
export { default as 'Swift' } from '../data/Swift.js'
export { default as 'SystemVerilog' } from '../data/SystemVerilog.js'
export { default as 'TI Program' } from '../data/TI_20_Program.js'
export { default as 'TL-Verilog' } from '../data/TL-Verilog.js'
export { default as 'TLA' } from '../data/TLA.js'
export { default as 'TOML' } from '../data/TOML.js'
export { default as 'TSPLIB data' } from '../data/TSPLIB_20_data.js'
export { default as 'TSQL' } from '../data/TSQL.js'
export { default as 'TSV' } from '../data/TSV.js'
export { default as 'TSX' } from '../data/TSX.js'
export { default as 'TXL' } from '../data/TXL.js'
export { default as 'Tact' } from '../data/Tact.js'
export { default as 'Talon' } from '../data/Talon.js'
export { default as 'Tcl' } from '../data/Tcl.js'
export { default as 'Tcsh' } from '../data/Tcsh.js'
export { default as 'TeX' } from '../data/TeX.js'
export { default as 'Tea' } from '../data/Tea.js'
export { default as 'Terra' } from '../data/Terra.js'
export { default as 'Terraform Template' } from '../data/Terraform_20_Template.js'
export { default as 'Texinfo' } from '../data/Texinfo.js'
export { default as 'Text' } from '../data/Text.js'
export { default as 'TextGrid' } from '../data/TextGrid.js'
export { default as 'TextMate Properties' } from '../data/TextMate_20_Properties.js'
export { default as 'Textile' } from '../data/Textile.js'
export { default as 'Thrift' } from '../data/Thrift.js'
export { default as 'Toit' } from '../data/Toit.js'
export { default as 'Tor Config' } from '../data/Tor_20_Config.js'
export { default as 'Tree-sitter Query' } from '../data/Tree-sitter_20_Query.js'
export { default as 'Turing' } from '../data/Turing.js'
export { default as 'Turtle' } from '../data/Turtle.js'
export { default as 'Twig' } from '../data/Twig.js'
export { default as 'Type Language' } from '../data/Type_20_Language.js'
export { default as 'TypeScript' } from '../data/TypeScript.js'
export { default as 'TypeSpec' } from '../data/TypeSpec.js'
export { default as 'Typst' } from '../data/Typst.js'
export { default as 'Unified Parallel C' } from '../data/Unified_20_Parallel_20_C.js'
export { default as 'Unity3D Asset' } from '../data/Unity3D_20_Asset.js'
export { default as 'Unix Assembly' } from '../data/Unix_20_Assembly.js'
export { default as 'Uno' } from '../data/Uno.js'
export { default as 'UnrealScript' } from '../data/UnrealScript.js'
export { default as 'Untyped Plutus Core' } from '../data/Untyped_20_Plutus_20_Core.js'
export { default as 'UrWeb' } from '../data/UrWeb.js'
export { default as 'V' } from '../data/V.js'
export { default as 'VBA' } from '../data/VBA.js'
export { default as 'VBScript' } from '../data/VBScript.js'
export { default as 'VCL' } from '../data/VCL.js'
export { default as 'VHDL' } from '../data/VHDL.js'
export { default as 'Vala' } from '../data/Vala.js'
export { default as 'Valve Data Format' } from '../data/Valve_20_Data_20_Format.js'
export { default as 'Velocity Template Language' } from '../data/Velocity_20_Template_20_Language.js'
export { default as 'Vento' } from '../data/Vento.js'
export { default as 'Verilog' } from '../data/Verilog.js'
export { default as 'Vim Help File' } from '../data/Vim_20_Help_20_File.js'
export { default as 'Vim Script' } from '../data/Vim_20_Script.js'
export { default as 'Vim Snippet' } from '../data/Vim_20_Snippet.js'
export { default as 'Visual Basic .NET' } from '../data/Visual_20_Basic_20_.NET.js'
export { default as 'Visual Basic 6.0' } from '../data/Visual_20_Basic_20_6.0.js'
export { default as 'Volt' } from '../data/Volt.js'
export { default as 'Vue' } from '../data/Vue.js'
export { default as 'Vyper' } from '../data/Vyper.js'
export { default as 'WDL' } from '../data/WDL.js'
export { default as 'WGSL' } from '../data/WGSL.js'
export { default as 'Wavefront Material' } from '../data/Wavefront_20_Material.js'
export { default as 'Wavefront Object' } from '../data/Wavefront_20_Object.js'
export { default as 'Web Ontology Language' } from '../data/Web_20_Ontology_20_Language.js'
export { default as 'WebAssembly' } from '../data/WebAssembly.js'
export { default as 'WebAssembly Interface Type' } from '../data/WebAssembly_20_Interface_20_Type.js'
export { default as 'WebIDL' } from '../data/WebIDL.js'
export { default as 'WebVTT' } from '../data/WebVTT.js'
export { default as 'Wget Config' } from '../data/Wget_20_Config.js'
export { default as 'Whiley' } from '../data/Whiley.js'
export { default as 'Wikitext' } from '../data/Wikitext.js'
export { default as 'Win32 Message File' } from '../data/Win32_20_Message_20_File.js'
export { default as 'Windows Registry Entries' } from '../data/Windows_20_Registry_20_Entries.js'
export { default as 'Witcher Script' } from '../data/Witcher_20_Script.js'
export { default as 'Wollok' } from '../data/Wollok.js'
export { default as 'World of Warcraft Addon Data' } from '../data/World_20_of_20_Warcraft_20_Addon_20_Data.js'
export { default as 'Wren' } from '../data/Wren.js'
export { default as 'X BitMap' } from '../data/X_20_BitMap.js'
export { default as 'X Font Directory Index' } from '../data/X_20_Font_20_Directory_20_Index.js'
export { default as 'X PixMap' } from '../data/X_20_PixMap.js'
export { default as 'X10' } from '../data/X10.js'
export { default as 'XC' } from '../data/XC.js'
export { default as 'XCompose' } from '../data/XCompose.js'
export { default as 'XML' } from '../data/XML.js'
export { default as 'XML Property List' } from '../data/XML_20_Property_20_List.js'
export { default as 'XPages' } from '../data/XPages.js'
export { default as 'XProc' } from '../data/XProc.js'
export { default as 'XQuery' } from '../data/XQuery.js'
export { default as 'XS' } from '../data/XS.js'
export { default as 'XSLT' } from '../data/XSLT.js'
export { default as 'Xmake' } from '../data/Xmake.js'
export { default as 'Xojo' } from '../data/Xojo.js'
export { default as 'Xonsh' } from '../data/Xonsh.js'
export { default as 'Xtend' } from '../data/Xtend.js'
export { default as 'YAML' } from '../data/YAML.js'
export { default as 'YANG' } from '../data/YANG.js'
export { default as 'YARA' } from '../data/YARA.js'
export { default as 'YASnippet' } from '../data/YASnippet.js'
export { default as 'Yacc' } from '../data/Yacc.js'
export { default as 'Yul' } from '../data/Yul.js'
export { default as 'ZAP' } from '../data/ZAP.js'
export { default as 'ZIL' } from '../data/ZIL.js'
export { default as 'Zeek' } from '../data/Zeek.js'
export { default as 'ZenScript' } from '../data/ZenScript.js'
export { default as 'Zephir' } from '../data/Zephir.js'
export { default as 'Zig' } from '../data/Zig.js'
export { default as 'Zimpl' } from '../data/Zimpl.js'
export { default as 'Zmodel' } from '../data/Zmodel.js'
export { default as 'cURL Config' } from '../data/cURL_20_Config.js'
export { default as 'crontab' } from '../data/crontab.js'
export { default as 'desktop' } from '../data/desktop.js'
export { default as 'dircolors' } from '../data/dircolors.js'
export { default as 'eC' } from '../data/eC.js'
export { default as 'edn' } from '../data/edn.js'
export { default as 'fish' } from '../data/fish.js'
export { default as 'hoon' } from '../data/hoon.js'
export { default as 'iCalendar' } from '../data/iCalendar.js'
export { default as 'jq' } from '../data/jq.js'
export { default as 'kvlang' } from '../data/kvlang.js'
export { default as 'mIRC Script' } from '../data/mIRC_20_Script.js'
export { default as 'mcfunction' } from '../data/mcfunction.js'
export { default as 'mdsvex' } from '../data/mdsvex.js'
export { default as 'mupad' } from '../data/mupad.js'
export { default as 'nanorc' } from '../data/nanorc.js'
export { default as 'nesC' } from '../data/nesC.js'
export { default as 'ooc' } from '../data/ooc.js'
export { default as 'q' } from '../data/q.js'
export { default as 'reStructuredText' } from '../data/reStructuredText.js'
export { default as 'robots.txt' } from '../data/robots.txt.js'
export { default as 'sed' } from '../data/sed.js'
export { default as 'templ' } from '../data/templ.js'
export { default as 'vCard' } from '../data/vCard.js'
export { default as 'wisp' } from '../data/wisp.js'
export { default as 'xBase' } from '../data/xBase.js'
