export type LanguageName =
  | '1C Enterprise'
  | '2-Dimensional Array'
  | '4D'
  | 'ABAP'
  | 'ABAP CDS'
  | 'ABNF'
  | 'AGS Script'
  | 'AIDL'
  | 'AL'
  | 'AMPL'
  | 'ANTLR'
  | 'API Blueprint'
  | 'APL'
  | 'ASL'
  | 'ASN.1'
  | 'ASP.NET'
  | 'ATS'
  | 'ActionScript'
  | 'Ada'
  | 'Adblock Filter List'
  | 'Adobe Font Metrics'
  | 'Agda'
  | 'Aiken'
  | 'Alloy'
  | 'Alpine Abuild'
  | 'Altium Designer'
  | 'AngelScript'
  | 'Answer Set Programming'
  | 'Ant Build System'
  | 'Antlers'
  | 'ApacheConf'
  | 'Apex'
  | 'Apollo Guidance Computer'
  | 'AppleScript'
  | 'Arc'
  | 'AsciiDoc'
  | 'AspectJ'
  | 'Assembly'
  | 'Astro'
  | 'Asymptote'
  | 'Augeas'
  | 'AutoHotkey'
  | 'AutoIt'
  | 'Avro IDL'
  | 'Awk'
  | 'B4X'
  | 'BASIC'
  | 'BQN'
  | 'Ballerina'
  | 'Batchfile'
  | 'Beef'
  | 'Befunge'
  | 'Berry'
  | 'BibTeX'
  | 'BibTeX Style'
  | 'Bicep'
  | 'Bikeshed'
  | 'Bison'
  | 'BitBake'
  | 'Blade'
  | 'BlitzBasic'
  | 'BlitzMax'
  | 'Bluespec'
  | 'Bluespec BH'
  | 'Boo'
  | 'Boogie'
  | 'Brainfuck'
  | 'BrighterScript'
  | 'Brightscript'
  | 'Browserslist'
  | 'BuildStream'
  | 'C'
  | 'C#'
  | 'C++'
  | 'C-ObjDump'
  | 'C2hs Haskell'
  | 'CAP CDS'
  | 'CIL'
  | 'CLIPS'
  | 'CMake'
  | 'COBOL'
  | 'CODEOWNERS'
  | 'COLLADA'
  | 'CSON'
  | 'CSS'
  | 'CSV'
  | 'CUE'
  | 'CWeb'
  | 'Cabal Config'
  | 'Caddyfile'
  | 'Cadence'
  | 'Cairo'
  | 'Cairo Zero'
  | 'CameLIGO'
  | "Cap'n Proto"
  | 'Carbon'
  | 'CartoCSS'
  | 'Ceylon'
  | 'Chapel'
  | 'Charity'
  | 'Checksums'
  | 'ChucK'
  | 'Circom'
  | 'Cirru'
  | 'Clarion'
  | 'Clarity'
  | 'Classic ASP'
  | 'Clean'
  | 'Click'
  | 'Clojure'
  | 'Closure Templates'
  | 'Cloud Firestore Security Rules'
  | 'Clue'
  | 'CoNLL-U'
  | 'CodeQL'
  | 'CoffeeScript'
  | 'ColdFusion'
  | 'ColdFusion CFC'
  | 'Common Lisp'
  | 'Common Workflow Language'
  | 'Component Pascal'
  | 'Cool'
  | 'Cpp-ObjDump'
  | 'Creole'
  | 'Crystal'
  | 'Csound'
  | 'Csound Document'
  | 'Csound Score'
  | 'Cuda'
  | 'Cue Sheet'
  | 'Curry'
  | 'Cycript'
  | 'Cylc'
  | 'Cypher'
  | 'Cython'
  | 'D'
  | 'D-ObjDump'
  | 'D2'
  | 'DIGITAL Command Language'
  | 'DM'
  | 'DNS Zone'
  | 'DTrace'
  | 'Dafny'
  | 'Darcs Patch'
  | 'Dart'
  | 'Daslang'
  | 'DataWeave'
  | 'Debian Package Control File'
  | 'DenizenScript'
  | 'Dhall'
  | 'Diff'
  | 'DirectX 3D File'
  | 'Dockerfile'
  | 'Dogescript'
  | 'Dotenv'
  | 'Dune'
  | 'Dylan'
  | 'E'
  | 'E-mail'
  | 'EBNF'
  | 'ECL'
  | 'ECLiPSe'
  | 'EJS'
  | 'EQ'
  | 'Eagle'
  | 'Earthly'
  | 'Easybuild'
  | 'Ecere Projects'
  | 'Ecmarkup'
  | 'Edge'
  | 'EdgeQL'
  | 'EditorConfig'
  | 'Edje Data Collection'
  | 'Eiffel'
  | 'Elixir'
  | 'Elm'
  | 'Elvish'
  | 'Elvish Transcript'
  | 'Emacs Lisp'
  | 'EmberScript'
  | 'Erlang'
  | 'Euphoria'
  | 'F#'
  | 'F*'
  | 'FIGlet Font'
  | 'FIRRTL'
  | 'FLUX'
  | 'Factor'
  | 'Fancy'
  | 'Fantom'
  | 'Faust'
  | 'Fennel'
  | 'Filebench WML'
  | 'Filterscript'
  | 'Fluent'
  | 'Formatted'
  | 'Forth'
  | 'Fortran'
  | 'Fortran Free Form'
  | 'FreeBASIC'
  | 'FreeMarker'
  | 'Frege'
  | 'Futhark'
  | 'G-code'
  | 'GAML'
  | 'GAMS'
  | 'GAP'
  | 'GCC Machine Description'
  | 'GDB'
  | 'GDScript'
  | 'GDShader'
  | 'GEDCOM'
  | 'GLSL'
  | 'GN'
  | 'GSC'
  | 'Game Maker Language'
  | 'Gemfile.lock'
  | 'Gemini'
  | 'Genero 4gl'
  | 'Genero per'
  | 'Genie'
  | 'Genshi'
  | 'Gentoo Ebuild'
  | 'Gentoo Eclass'
  | 'Gerber Image'
  | 'Gettext Catalog'
  | 'Gherkin'
  | 'Git Attributes'
  | 'Git Config'
  | 'Git Revision List'
  | 'Gleam'
  | 'Glimmer JS'
  | 'Glimmer TS'
  | 'Glyph'
  | 'Glyph Bitmap Distribution Format'
  | 'Gnuplot'
  | 'Go'
  | 'Go Checksums'
  | 'Go Module'
  | 'Go Workspace'
  | 'Godot Resource'
  | 'Golo'
  | 'Gosu'
  | 'Grace'
  | 'Gradle'
  | 'Gradle Kotlin DSL'
  | 'Grammatical Framework'
  | 'Graph Modeling Language'
  | 'GraphQL'
  | 'Graphviz (DOT)'
  | 'Groovy'
  | 'Groovy Server Pages'
  | 'HAProxy'
  | 'HCL'
  | 'HIP'
  | 'HLSL'
  | 'HOCON'
  | 'HTML'
  | 'HTML+ECR'
  | 'HTML+EEX'
  | 'HTML+ERB'
  | 'HTML+PHP'
  | 'HTML+Razor'
  | 'HTTP'
  | 'HXML'
  | 'Hack'
  | 'Haml'
  | 'Handlebars'
  | 'Harbour'
  | 'Hare'
  | 'Haskell'
  | 'Haxe'
  | 'HiveQL'
  | 'HolyC'
  | 'Hosts File'
  | 'Hy'
  | 'HyPhy'
  | 'IDL'
  | 'IGOR Pro'
  | 'INI'
  | 'IRC log'
  | 'ISPC'
  | 'Idris'
  | 'Ignore List'
  | 'ImageJ Macro'
  | 'Imba'
  | 'Inform 7'
  | 'Ink'
  | 'Inno Setup'
  | 'Io'
  | 'Ioke'
  | 'Isabelle'
  | 'Isabelle ROOT'
  | 'J'
  | 'JAR Manifest'
  | 'JCL'
  | 'JFlex'
  | 'JSON'
  | 'JSON with Comments'
  | 'JSON5'
  | 'JSONLD'
  | 'JSONiq'
  | 'Jai'
  | 'Janet'
  | 'Jasmin'
  | 'Java'
  | 'Java Properties'
  | 'Java Server Pages'
  | 'Java Template Engine'
  | 'JavaScript'
  | 'JavaScript+ERB'
  | 'Jest Snapshot'
  | 'JetBrains MPS'
  | 'Jinja'
  | 'Jison'
  | 'Jison Lex'
  | 'Jolie'
  | 'Jsonnet'
  | 'Julia'
  | 'Julia REPL'
  | 'Jupyter Notebook'
  | 'Just'
  | 'KDL'
  | 'KRL'
  | 'Kaitai Struct'
  | 'KakouneScript'
  | 'KerboScript'
  | 'KiCad Layout'
  | 'KiCad Legacy Layout'
  | 'KiCad Schematic'
  | 'Kickstart'
  | 'Kit'
  | 'Koka'
  | 'Kotlin'
  | 'Kusto'
  | 'LFE'
  | 'LLVM'
  | 'LOLCODE'
  | 'LSL'
  | 'LTspice Symbol'
  | 'LabVIEW'
  | 'Lark'
  | 'Lasso'
  | 'Latte'
  | 'Lean'
  | 'Lean 4'
  | 'Leo'
  | 'Less'
  | 'Lex'
  | 'LigoLANG'
  | 'LilyPond'
  | 'Limbo'
  | 'Linear Programming'
  | 'Linker Script'
  | 'Linux Kernel Module'
  | 'Liquid'
  | 'Literate Agda'
  | 'Literate CoffeeScript'
  | 'Literate Haskell'
  | 'LiveCode Script'
  | 'LiveScript'
  | 'Logos'
  | 'Logtalk'
  | 'LookML'
  | 'LoomScript'
  | 'Lua'
  | 'Luau'
  | 'M'
  | 'M3U'
  | 'M4'
  | 'M4Sugar'
  | 'MATLAB'
  | 'MAXScript'
  | 'MDX'
  | 'MLIR'
  | 'MQL4'
  | 'MQL5'
  | 'MTML'
  | 'MUF'
  | 'Macaulay2'
  | 'Makefile'
  | 'Mako'
  | 'Markdown'
  | 'Marko'
  | 'Mask'
  | 'Mathematica'
  | 'Maven POM'
  | 'Max'
  | 'Mercury'
  | 'Mermaid'
  | 'Meson'
  | 'Metal'
  | 'Microsoft Developer Studio Project'
  | 'Microsoft Visual Studio Solution'
  | 'MiniD'
  | 'MiniYAML'
  | 'MiniZinc'
  | 'MiniZinc Data'
  | 'Mint'
  | 'Mirah'
  | 'Modelica'
  | 'Modula-2'
  | 'Modula-3'
  | 'Module Management System'
  | 'Mojo'
  | 'Monkey'
  | 'Monkey C'
  | 'Moocode'
  | 'MoonBit'
  | 'MoonScript'
  | 'Motoko'
  | 'Motorola 68K Assembly'
  | 'Move'
  | 'Muse'
  | 'Mustache'
  | 'Myghty'
  | 'NASL'
  | 'NCL'
  | 'NEON'
  | 'NL'
  | 'NMODL'
  | 'NPM Config'
  | 'NSIS'
  | 'NWScript'
  | 'Nasal'
  | 'Nearley'
  | 'Nemerle'
  | 'NetLinx'
  | 'NetLinx+ERB'
  | 'NetLogo'
  | 'NewLisp'
  | 'Nextflow'
  | 'Nginx'
  | 'Nim'
  | 'Ninja'
  | 'Nit'
  | 'Nix'
  | 'Noir'
  | 'Nu'
  | 'NumPy'
  | 'Nunjucks'
  | 'Nushell'
  | 'OASv2-json'
  | 'OASv2-yaml'
  | 'OASv3-json'
  | 'OASv3-yaml'
  | 'OCaml'
  | 'OMNeT++ MSG'
  | 'OMNeT++ NED'
  | 'Oberon'
  | 'ObjDump'
  | 'Object Data Instance Notation'
  | 'ObjectScript'
  | 'Objective-C'
  | 'Objective-C++'
  | 'Objective-J'
  | 'Odin'
  | 'Omgrofl'
  | 'Opa'
  | 'Opal'
  | 'Open Policy Agent'
  | 'OpenAPI Specification v2'
  | 'OpenAPI Specification v3'
  | 'OpenCL'
  | 'OpenEdge ABL'
  | 'OpenQASM'
  | 'OpenRC runscript'
  | 'OpenSCAD'
  | 'OpenStep Property List'
  | 'OpenType Feature File'
  | 'Option List'
  | 'Org'
  | 'OverpassQL'
  | 'Ox'
  | 'Oxygene'
  | 'Oz'
  | 'P4'
  | 'PDDL'
  | 'PEG.js'
  | 'PHP'
  | 'PLSQL'
  | 'PLpgSQL'
  | 'POV-Ray SDL'
  | 'Pact'
  | 'Pan'
  | 'Papyrus'
  | 'Parrot'
  | 'Parrot Assembly'
  | 'Parrot Internal Representation'
  | 'Pascal'
  | 'Pawn'
  | 'Pep8'
  | 'Perl'
  | 'Pic'
  | 'Pickle'
  | 'PicoLisp'
  | 'PigLatin'
  | 'Pike'
  | 'Pip Requirements'
  | 'Pkl'
  | 'PlantUML'
  | 'Pod'
  | 'Pod 6'
  | 'PogoScript'
  | 'Polar'
  | 'Pony'
  | 'Portugol'
  | 'PostCSS'
  | 'PostScript'
  | 'PowerBuilder'
  | 'PowerShell'
  | 'Praat'
  | 'Prisma'
  | 'Processing'
  | 'Procfile'
  | 'Proguard'
  | 'Prolog'
  | 'Promela'
  | 'Propeller Spin'
  | 'Protocol Buffer'
  | 'Protocol Buffer Text Format'
  | 'Public Key'
  | 'Pug'
  | 'Puppet'
  | 'Pure Data'
  | 'PureBasic'
  | 'PureScript'
  | 'Pyret'
  | 'Python'
  | 'Python console'
  | 'Python traceback'
  | 'Q#'
  | 'QML'
  | 'QMake'
  | 'Qt Script'
  | 'Quake'
  | 'QuickBASIC'
  | 'R'
  | 'RAML'
  | 'RBS'
  | 'RDoc'
  | 'REALbasic'
  | 'REXX'
  | 'RMarkdown'
  | 'RON'
  | 'RPC'
  | 'RPGLE'
  | 'RPM Spec'
  | 'RUNOFF'
  | 'Racket'
  | 'Ragel'
  | 'Raku'
  | 'Rascal'
  | 'Raw token data'
  | 'ReScript'
  | 'Readline Config'
  | 'Reason'
  | 'ReasonLIGO'
  | 'Rebol'
  | 'Record Jar'
  | 'Red'
  | 'Redcode'
  | 'Redirect Rules'
  | 'Regular Expression'
  | "Ren'Py"
  | 'RenderScript'
  | 'Rez'
  | 'Rich Text Format'
  | 'Ring'
  | 'Riot'
  | 'RobotFramework'
  | 'Roc'
  | 'Rocq Prover'
  | 'Roff'
  | 'Roff Manpage'
  | 'Rouge'
  | 'RouterOS Script'
  | 'Ruby'
  | 'Rust'
  | 'SAS'
  | 'SCSS'
  | 'SELinux Policy'
  | 'SMT'
  | 'SPARQL'
  | 'SQF'
  | 'SQL'
  | 'SQLPL'
  | 'SRecode Template'
  | 'SSH Config'
  | 'STAR'
  | 'STL'
  | 'STON'
  | 'SVG'
  | 'SWIG'
  | 'Sage'
  | 'Sail'
  | 'SaltStack'
  | 'Sass'
  | 'Scala'
  | 'Scaml'
  | 'Scenic'
  | 'Scheme'
  | 'Scilab'
  | 'Self'
  | 'ShaderLab'
  | 'Shell'
  | 'ShellCheck Config'
  | 'ShellSession'
  | 'Shen'
  | 'Sieve'
  | 'Simple File Verification'
  | 'Singularity'
  | 'Slang'
  | 'Slash'
  | 'Slice'
  | 'Slim'
  | 'Slint'
  | 'SmPL'
  | 'Smali'
  | 'Smalltalk'
  | 'Smarty'
  | 'Smithy'
  | 'Snakemake'
  | 'Solidity'
  | 'Soong'
  | 'SourcePawn'
  | 'Spline Font Database'
  | 'Squirrel'
  | 'Stan'
  | 'Standard ML'
  | 'Starlark'
  | 'Stata'
  | 'StringTemplate'
  | 'Stylus'
  | 'SubRip Text'
  | 'SugarSS'
  | 'SuperCollider'
  | 'Survex data'
  | 'Svelte'
  | 'Sway'
  | 'Sweave'
  | 'Swift'
  | 'SystemVerilog'
  | 'TI Program'
  | 'TL-Verilog'
  | 'TLA'
  | 'TOML'
  | 'TSPLIB data'
  | 'TSQL'
  | 'TSV'
  | 'TSX'
  | 'TXL'
  | 'Tact'
  | 'Talon'
  | 'Tcl'
  | 'Tcsh'
  | 'TeX'
  | 'Tea'
  | 'Terra'
  | 'Terraform Template'
  | 'Texinfo'
  | 'Text'
  | 'TextGrid'
  | 'TextMate Properties'
  | 'Textile'
  | 'Thrift'
  | 'Toit'
  | 'Tor Config'
  | 'Tree-sitter Query'
  | 'Turing'
  | 'Turtle'
  | 'Twig'
  | 'Type Language'
  | 'TypeScript'
  | 'TypeSpec'
  | 'Typst'
  | 'Unified Parallel C'
  | 'Unity3D Asset'
  | 'Unix Assembly'
  | 'Uno'
  | 'UnrealScript'
  | 'Untyped Plutus Core'
  | 'UrWeb'
  | 'V'
  | 'VBA'
  | 'VBScript'
  | 'VCL'
  | 'VHDL'
  | 'Vala'
  | 'Valve Data Format'
  | 'Velocity Template Language'
  | 'Vento'
  | 'Verilog'
  | 'Vim Help File'
  | 'Vim Script'
  | 'Vim Snippet'
  | 'Visual Basic .NET'
  | 'Visual Basic 6.0'
  | 'Volt'
  | 'Vue'
  | 'Vyper'
  | 'WDL'
  | 'WGSL'
  | 'Wavefront Material'
  | 'Wavefront Object'
  | 'Web Ontology Language'
  | 'WebAssembly'
  | 'WebAssembly Interface Type'
  | 'WebIDL'
  | 'WebVTT'
  | 'Wget Config'
  | 'Whiley'
  | 'Wikitext'
  | 'Win32 Message File'
  | 'Windows Registry Entries'
  | 'Witcher Script'
  | 'Wollok'
  | 'World of Warcraft Addon Data'
  | 'Wren'
  | 'X BitMap'
  | 'X Font Directory Index'
  | 'X PixMap'
  | 'X10'
  | 'XC'
  | 'XCompose'
  | 'XML'
  | 'XML Property List'
  | 'XPages'
  | 'XProc'
  | 'XQuery'
  | 'XS'
  | 'XSLT'
  | 'Xmake'
  | 'Xojo'
  | 'Xonsh'
  | 'Xtend'
  | 'YAML'
  | 'YANG'
  | 'YARA'
  | 'YASnippet'
  | 'Yacc'
  | 'Yul'
  | 'ZAP'
  | 'ZIL'
  | 'Zeek'
  | 'ZenScript'
  | 'Zephir'
  | 'Zig'
  | 'Zimpl'
  | 'Zmodel'
  | 'cURL Config'
  | 'crontab'
  | 'desktop'
  | 'dircolors'
  | 'eC'
  | 'edn'
  | 'fish'
  | 'hoon'
  | 'iCalendar'
  | 'jq'
  | 'kvlang'
  | 'mIRC Script'
  | 'mcfunction'
  | 'mdsvex'
  | 'mupad'
  | 'nanorc'
  | 'nesC'
  | 'ooc'
  | 'q'
  | 'reStructuredText'
  | 'robots.txt'
  | 'sed'
  | 'templ'
  | 'vCard'
  | 'wisp'
  | 'xBase'

export interface Language {
  /**
   * Language name.
   */
  name: string
  /**
   * Either data, programming, markup, prose, or nil
   */
  type: string
  /**
   * CSS hex color to represent the language. Only used if type is "programming" or "markup".
   */
  color?: string
  /**
   * An Array of associated extensions (the first one is
   * considered the primary extension, the others should be
   * listed alphabetically)
   */
  extensions?: string[]
  /**
   * The TextMate scope that represents this programming
   * language. This should match one of the scopes listed in
   * the grammars.yml file. Use "none" if there is no grammar
   * for this language.
   */
  tmScope: string
  /**
   * A String name of the Ace Mode used for highlighting whenever
   * a file is edited. This must match one of the filenames in https://gh.io/acemodes.
   * Use "text" if a mode does not exist.
   */
  aceMode: string
  /**
   * Integer used as a language-name-independent indexed field so that we can rename
   * languages in Linguist without reindexing all the code on GitHub. Must not be
   * changed for existing languages without the explicit permission of GitHub staff.
   */
  languageId: number
  /**
   * An Array of additional aliases (implicitly
   * includes name.downcase)
   */
  aliases?: string[]
  /**
   * A String name of the CodeMirror Mode used for highlighting whenever a file is edited.
   * This must match a mode from https://git.io/vi9Fx
   */
  codemirrorMode?: string
  /**
   * A String name of the file mime type used for highlighting whenever a file is edited.
   * This should match the `mime` associated with the mode from https://git.io/f4SoQ
   */
  codemirrorMimeType?: string
  /**
   * An Array of associated interpreters
   */
  interpreters?: string[]
  /**
   * Name of the parent language. Languages in a group are counted
   * in the statistics as the parent language.
   */
  group?: string
  /**
   * An Array of filenames commonly associated with the language
   */
  filenames?: string[]
  /**
   * Boolean wrap to enable line wrapping (default: false)
   */
  wrap?: boolean
}

export type { default as '1C Enterprise' } from '../data/1C_20_Enterprise.mjs'
export type { default as '2-Dimensional Array' } from '../data/2-Dimensional_20_Array.mjs'
export type { default as '4D' } from '../data/4D.mjs'
export type { default as 'ABAP' } from '../data/ABAP.mjs'
export type { default as 'ABAP CDS' } from '../data/ABAP_20_CDS.mjs'
export type { default as 'ABNF' } from '../data/ABNF.mjs'
export type { default as 'AGS Script' } from '../data/AGS_20_Script.mjs'
export type { default as 'AIDL' } from '../data/AIDL.mjs'
export type { default as 'AL' } from '../data/AL.mjs'
export type { default as 'AMPL' } from '../data/AMPL.mjs'
export type { default as 'ANTLR' } from '../data/ANTLR.mjs'
export type { default as 'API Blueprint' } from '../data/API_20_Blueprint.mjs'
export type { default as 'APL' } from '../data/APL.mjs'
export type { default as 'ASL' } from '../data/ASL.mjs'
export type { default as 'ASN.1' } from '../data/ASN.1.mjs'
export type { default as 'ASP.NET' } from '../data/ASP.NET.mjs'
export type { default as 'ATS' } from '../data/ATS.mjs'
export type { default as 'ActionScript' } from '../data/ActionScript.mjs'
export type { default as 'Ada' } from '../data/Ada.mjs'
export type { default as 'Adblock Filter List' } from '../data/Adblock_20_Filter_20_List.mjs'
export type { default as 'Adobe Font Metrics' } from '../data/Adobe_20_Font_20_Metrics.mjs'
export type { default as 'Agda' } from '../data/Agda.mjs'
export type { default as 'Aiken' } from '../data/Aiken.mjs'
export type { default as 'Alloy' } from '../data/Alloy.mjs'
export type { default as 'Alpine Abuild' } from '../data/Alpine_20_Abuild.mjs'
export type { default as 'Altium Designer' } from '../data/Altium_20_Designer.mjs'
export type { default as 'AngelScript' } from '../data/AngelScript.mjs'
export type { default as 'Answer Set Programming' } from '../data/Answer_20_Set_20_Programming.mjs'
export type { default as 'Ant Build System' } from '../data/Ant_20_Build_20_System.mjs'
export type { default as 'Antlers' } from '../data/Antlers.mjs'
export type { default as 'ApacheConf' } from '../data/ApacheConf.mjs'
export type { default as 'Apex' } from '../data/Apex.mjs'
export type { default as 'Apollo Guidance Computer' } from '../data/Apollo_20_Guidance_20_Computer.mjs'
export type { default as 'AppleScript' } from '../data/AppleScript.mjs'
export type { default as 'Arc' } from '../data/Arc.mjs'
export type { default as 'AsciiDoc' } from '../data/AsciiDoc.mjs'
export type { default as 'AspectJ' } from '../data/AspectJ.mjs'
export type { default as 'Assembly' } from '../data/Assembly.mjs'
export type { default as 'Astro' } from '../data/Astro.mjs'
export type { default as 'Asymptote' } from '../data/Asymptote.mjs'
export type { default as 'Augeas' } from '../data/Augeas.mjs'
export type { default as 'AutoHotkey' } from '../data/AutoHotkey.mjs'
export type { default as 'AutoIt' } from '../data/AutoIt.mjs'
export type { default as 'Avro IDL' } from '../data/Avro_20_IDL.mjs'
export type { default as 'Awk' } from '../data/Awk.mjs'
export type { default as 'B4X' } from '../data/B4X.mjs'
export type { default as 'BASIC' } from '../data/BASIC.mjs'
export type { default as 'BQN' } from '../data/BQN.mjs'
export type { default as 'Ballerina' } from '../data/Ballerina.mjs'
export type { default as 'Batchfile' } from '../data/Batchfile.mjs'
export type { default as 'Beef' } from '../data/Beef.mjs'
export type { default as 'Befunge' } from '../data/Befunge.mjs'
export type { default as 'Berry' } from '../data/Berry.mjs'
export type { default as 'BibTeX' } from '../data/BibTeX.mjs'
export type { default as 'BibTeX Style' } from '../data/BibTeX_20_Style.mjs'
export type { default as 'Bicep' } from '../data/Bicep.mjs'
export type { default as 'Bikeshed' } from '../data/Bikeshed.mjs'
export type { default as 'Bison' } from '../data/Bison.mjs'
export type { default as 'BitBake' } from '../data/BitBake.mjs'
export type { default as 'Blade' } from '../data/Blade.mjs'
export type { default as 'BlitzBasic' } from '../data/BlitzBasic.mjs'
export type { default as 'BlitzMax' } from '../data/BlitzMax.mjs'
export type { default as 'Bluespec' } from '../data/Bluespec.mjs'
export type { default as 'Bluespec BH' } from '../data/Bluespec_20_BH.mjs'
export type { default as 'Boo' } from '../data/Boo.mjs'
export type { default as 'Boogie' } from '../data/Boogie.mjs'
export type { default as 'Brainfuck' } from '../data/Brainfuck.mjs'
export type { default as 'BrighterScript' } from '../data/BrighterScript.mjs'
export type { default as 'Brightscript' } from '../data/Brightscript.mjs'
export type { default as 'Browserslist' } from '../data/Browserslist.mjs'
export type { default as 'BuildStream' } from '../data/BuildStream.mjs'
export type { default as 'C' } from '../data/C.mjs'
export type { default as 'C#' } from '../data/C_23_.mjs'
export type { default as 'C++' } from '../data/C_2b__2b_.mjs'
export type { default as 'C-ObjDump' } from '../data/C-ObjDump.mjs'
export type { default as 'C2hs Haskell' } from '../data/C2hs_20_Haskell.mjs'
export type { default as 'CAP CDS' } from '../data/CAP_20_CDS.mjs'
export type { default as 'CIL' } from '../data/CIL.mjs'
export type { default as 'CLIPS' } from '../data/CLIPS.mjs'
export type { default as 'CMake' } from '../data/CMake.mjs'
export type { default as 'COBOL' } from '../data/COBOL.mjs'
export type { default as 'CODEOWNERS' } from '../data/CODEOWNERS.mjs'
export type { default as 'COLLADA' } from '../data/COLLADA.mjs'
export type { default as 'CSON' } from '../data/CSON.mjs'
export type { default as 'CSS' } from '../data/CSS.mjs'
export type { default as 'CSV' } from '../data/CSV.mjs'
export type { default as 'CUE' } from '../data/CUE.mjs'
export type { default as 'CWeb' } from '../data/CWeb.mjs'
export type { default as 'Cabal Config' } from '../data/Cabal_20_Config.mjs'
export type { default as 'Caddyfile' } from '../data/Caddyfile.mjs'
export type { default as 'Cadence' } from '../data/Cadence.mjs'
export type { default as 'Cairo' } from '../data/Cairo.mjs'
export type { default as 'Cairo Zero' } from '../data/Cairo_20_Zero.mjs'
export type { default as 'CameLIGO' } from '../data/CameLIGO.mjs'
export type { default as "Cap'n Proto" } from '../data/Cap_27_n_20_Proto.mjs'
export type { default as 'Carbon' } from '../data/Carbon.mjs'
export type { default as 'CartoCSS' } from '../data/CartoCSS.mjs'
export type { default as 'Ceylon' } from '../data/Ceylon.mjs'
export type { default as 'Chapel' } from '../data/Chapel.mjs'
export type { default as 'Charity' } from '../data/Charity.mjs'
export type { default as 'Checksums' } from '../data/Checksums.mjs'
export type { default as 'ChucK' } from '../data/ChucK.mjs'
export type { default as 'Circom' } from '../data/Circom.mjs'
export type { default as 'Cirru' } from '../data/Cirru.mjs'
export type { default as 'Clarion' } from '../data/Clarion.mjs'
export type { default as 'Clarity' } from '../data/Clarity.mjs'
export type { default as 'Classic ASP' } from '../data/Classic_20_ASP.mjs'
export type { default as 'Clean' } from '../data/Clean.mjs'
export type { default as 'Click' } from '../data/Click.mjs'
export type { default as 'Clojure' } from '../data/Clojure.mjs'
export type { default as 'Closure Templates' } from '../data/Closure_20_Templates.mjs'
export type { default as 'Cloud Firestore Security Rules' } from '../data/Cloud_20_Firestore_20_Security_20_Rules.mjs'
export type { default as 'Clue' } from '../data/Clue.mjs'
export type { default as 'CoNLL-U' } from '../data/CoNLL-U.mjs'
export type { default as 'CodeQL' } from '../data/CodeQL.mjs'
export type { default as 'CoffeeScript' } from '../data/CoffeeScript.mjs'
export type { default as 'ColdFusion' } from '../data/ColdFusion.mjs'
export type { default as 'ColdFusion CFC' } from '../data/ColdFusion_20_CFC.mjs'
export type { default as 'Common Lisp' } from '../data/Common_20_Lisp.mjs'
export type { default as 'Common Workflow Language' } from '../data/Common_20_Workflow_20_Language.mjs'
export type { default as 'Component Pascal' } from '../data/Component_20_Pascal.mjs'
export type { default as 'Cool' } from '../data/Cool.mjs'
export type { default as 'Cpp-ObjDump' } from '../data/Cpp-ObjDump.mjs'
export type { default as 'Creole' } from '../data/Creole.mjs'
export type { default as 'Crystal' } from '../data/Crystal.mjs'
export type { default as 'Csound' } from '../data/Csound.mjs'
export type { default as 'Csound Document' } from '../data/Csound_20_Document.mjs'
export type { default as 'Csound Score' } from '../data/Csound_20_Score.mjs'
export type { default as 'Cuda' } from '../data/Cuda.mjs'
export type { default as 'Cue Sheet' } from '../data/Cue_20_Sheet.mjs'
export type { default as 'Curry' } from '../data/Curry.mjs'
export type { default as 'Cycript' } from '../data/Cycript.mjs'
export type { default as 'Cylc' } from '../data/Cylc.mjs'
export type { default as 'Cypher' } from '../data/Cypher.mjs'
export type { default as 'Cython' } from '../data/Cython.mjs'
export type { default as 'D' } from '../data/D.mjs'
export type { default as 'D-ObjDump' } from '../data/D-ObjDump.mjs'
export type { default as 'D2' } from '../data/D2.mjs'
export type { default as 'DIGITAL Command Language' } from '../data/DIGITAL_20_Command_20_Language.mjs'
export type { default as 'DM' } from '../data/DM.mjs'
export type { default as 'DNS Zone' } from '../data/DNS_20_Zone.mjs'
export type { default as 'DTrace' } from '../data/DTrace.mjs'
export type { default as 'Dafny' } from '../data/Dafny.mjs'
export type { default as 'Darcs Patch' } from '../data/Darcs_20_Patch.mjs'
export type { default as 'Dart' } from '../data/Dart.mjs'
export type { default as 'Daslang' } from '../data/Daslang.mjs'
export type { default as 'DataWeave' } from '../data/DataWeave.mjs'
export type { default as 'Debian Package Control File' } from '../data/Debian_20_Package_20_Control_20_File.mjs'
export type { default as 'DenizenScript' } from '../data/DenizenScript.mjs'
export type { default as 'Dhall' } from '../data/Dhall.mjs'
export type { default as 'Diff' } from '../data/Diff.mjs'
export type { default as 'DirectX 3D File' } from '../data/DirectX_20_3D_20_File.mjs'
export type { default as 'Dockerfile' } from '../data/Dockerfile.mjs'
export type { default as 'Dogescript' } from '../data/Dogescript.mjs'
export type { default as 'Dotenv' } from '../data/Dotenv.mjs'
export type { default as 'Dune' } from '../data/Dune.mjs'
export type { default as 'Dylan' } from '../data/Dylan.mjs'
export type { default as 'E' } from '../data/E.mjs'
export type { default as 'E-mail' } from '../data/E-mail.mjs'
export type { default as 'EBNF' } from '../data/EBNF.mjs'
export type { default as 'ECL' } from '../data/ECL.mjs'
export type { default as 'ECLiPSe' } from '../data/ECLiPSe.mjs'
export type { default as 'EJS' } from '../data/EJS.mjs'
export type { default as 'EQ' } from '../data/EQ.mjs'
export type { default as 'Eagle' } from '../data/Eagle.mjs'
export type { default as 'Earthly' } from '../data/Earthly.mjs'
export type { default as 'Easybuild' } from '../data/Easybuild.mjs'
export type { default as 'Ecere Projects' } from '../data/Ecere_20_Projects.mjs'
export type { default as 'Ecmarkup' } from '../data/Ecmarkup.mjs'
export type { default as 'Edge' } from '../data/Edge.mjs'
export type { default as 'EdgeQL' } from '../data/EdgeQL.mjs'
export type { default as 'EditorConfig' } from '../data/EditorConfig.mjs'
export type { default as 'Edje Data Collection' } from '../data/Edje_20_Data_20_Collection.mjs'
export type { default as 'Eiffel' } from '../data/Eiffel.mjs'
export type { default as 'Elixir' } from '../data/Elixir.mjs'
export type { default as 'Elm' } from '../data/Elm.mjs'
export type { default as 'Elvish' } from '../data/Elvish.mjs'
export type { default as 'Elvish Transcript' } from '../data/Elvish_20_Transcript.mjs'
export type { default as 'Emacs Lisp' } from '../data/Emacs_20_Lisp.mjs'
export type { default as 'EmberScript' } from '../data/EmberScript.mjs'
export type { default as 'Erlang' } from '../data/Erlang.mjs'
export type { default as 'Euphoria' } from '../data/Euphoria.mjs'
export type { default as 'F#' } from '../data/F_23_.mjs'
export type { default as 'F*' } from '../data/F_2a_.mjs'
export type { default as 'FIGlet Font' } from '../data/FIGlet_20_Font.mjs'
export type { default as 'FIRRTL' } from '../data/FIRRTL.mjs'
export type { default as 'FLUX' } from '../data/FLUX.mjs'
export type { default as 'Factor' } from '../data/Factor.mjs'
export type { default as 'Fancy' } from '../data/Fancy.mjs'
export type { default as 'Fantom' } from '../data/Fantom.mjs'
export type { default as 'Faust' } from '../data/Faust.mjs'
export type { default as 'Fennel' } from '../data/Fennel.mjs'
export type { default as 'Filebench WML' } from '../data/Filebench_20_WML.mjs'
export type { default as 'Filterscript' } from '../data/Filterscript.mjs'
export type { default as 'Fluent' } from '../data/Fluent.mjs'
export type { default as 'Formatted' } from '../data/Formatted.mjs'
export type { default as 'Forth' } from '../data/Forth.mjs'
export type { default as 'Fortran' } from '../data/Fortran.mjs'
export type { default as 'Fortran Free Form' } from '../data/Fortran_20_Free_20_Form.mjs'
export type { default as 'FreeBASIC' } from '../data/FreeBASIC.mjs'
export type { default as 'FreeMarker' } from '../data/FreeMarker.mjs'
export type { default as 'Frege' } from '../data/Frege.mjs'
export type { default as 'Futhark' } from '../data/Futhark.mjs'
export type { default as 'G-code' } from '../data/G-code.mjs'
export type { default as 'GAML' } from '../data/GAML.mjs'
export type { default as 'GAMS' } from '../data/GAMS.mjs'
export type { default as 'GAP' } from '../data/GAP.mjs'
export type { default as 'GCC Machine Description' } from '../data/GCC_20_Machine_20_Description.mjs'
export type { default as 'GDB' } from '../data/GDB.mjs'
export type { default as 'GDScript' } from '../data/GDScript.mjs'
export type { default as 'GDShader' } from '../data/GDShader.mjs'
export type { default as 'GEDCOM' } from '../data/GEDCOM.mjs'
export type { default as 'GLSL' } from '../data/GLSL.mjs'
export type { default as 'GN' } from '../data/GN.mjs'
export type { default as 'GSC' } from '../data/GSC.mjs'
export type { default as 'Game Maker Language' } from '../data/Game_20_Maker_20_Language.mjs'
export type { default as 'Gemfile.lock' } from '../data/Gemfile.lock.mjs'
export type { default as 'Gemini' } from '../data/Gemini.mjs'
export type { default as 'Genero 4gl' } from '../data/Genero_20_4gl.mjs'
export type { default as 'Genero per' } from '../data/Genero_20_per.mjs'
export type { default as 'Genie' } from '../data/Genie.mjs'
export type { default as 'Genshi' } from '../data/Genshi.mjs'
export type { default as 'Gentoo Ebuild' } from '../data/Gentoo_20_Ebuild.mjs'
export type { default as 'Gentoo Eclass' } from '../data/Gentoo_20_Eclass.mjs'
export type { default as 'Gerber Image' } from '../data/Gerber_20_Image.mjs'
export type { default as 'Gettext Catalog' } from '../data/Gettext_20_Catalog.mjs'
export type { default as 'Gherkin' } from '../data/Gherkin.mjs'
export type { default as 'Git Attributes' } from '../data/Git_20_Attributes.mjs'
export type { default as 'Git Config' } from '../data/Git_20_Config.mjs'
export type { default as 'Git Revision List' } from '../data/Git_20_Revision_20_List.mjs'
export type { default as 'Gleam' } from '../data/Gleam.mjs'
export type { default as 'Glimmer JS' } from '../data/Glimmer_20_JS.mjs'
export type { default as 'Glimmer TS' } from '../data/Glimmer_20_TS.mjs'
export type { default as 'Glyph' } from '../data/Glyph.mjs'
export type { default as 'Glyph Bitmap Distribution Format' } from '../data/Glyph_20_Bitmap_20_Distribution_20_Format.mjs'
export type { default as 'Gnuplot' } from '../data/Gnuplot.mjs'
export type { default as 'Go' } from '../data/Go.mjs'
export type { default as 'Go Checksums' } from '../data/Go_20_Checksums.mjs'
export type { default as 'Go Module' } from '../data/Go_20_Module.mjs'
export type { default as 'Go Workspace' } from '../data/Go_20_Workspace.mjs'
export type { default as 'Godot Resource' } from '../data/Godot_20_Resource.mjs'
export type { default as 'Golo' } from '../data/Golo.mjs'
export type { default as 'Gosu' } from '../data/Gosu.mjs'
export type { default as 'Grace' } from '../data/Grace.mjs'
export type { default as 'Gradle' } from '../data/Gradle.mjs'
export type { default as 'Gradle Kotlin DSL' } from '../data/Gradle_20_Kotlin_20_DSL.mjs'
export type { default as 'Grammatical Framework' } from '../data/Grammatical_20_Framework.mjs'
export type { default as 'Graph Modeling Language' } from '../data/Graph_20_Modeling_20_Language.mjs'
export type { default as 'GraphQL' } from '../data/GraphQL.mjs'
export type { default as 'Graphviz (DOT)' } from '../data/Graphviz_20__28_DOT_29_.mjs'
export type { default as 'Groovy' } from '../data/Groovy.mjs'
export type { default as 'Groovy Server Pages' } from '../data/Groovy_20_Server_20_Pages.mjs'
export type { default as 'HAProxy' } from '../data/HAProxy.mjs'
export type { default as 'HCL' } from '../data/HCL.mjs'
export type { default as 'HIP' } from '../data/HIP.mjs'
export type { default as 'HLSL' } from '../data/HLSL.mjs'
export type { default as 'HOCON' } from '../data/HOCON.mjs'
export type { default as 'HTML' } from '../data/HTML.mjs'
export type { default as 'HTML+ECR' } from '../data/HTML_2b_ECR.mjs'
export type { default as 'HTML+EEX' } from '../data/HTML_2b_EEX.mjs'
export type { default as 'HTML+ERB' } from '../data/HTML_2b_ERB.mjs'
export type { default as 'HTML+PHP' } from '../data/HTML_2b_PHP.mjs'
export type { default as 'HTML+Razor' } from '../data/HTML_2b_Razor.mjs'
export type { default as 'HTTP' } from '../data/HTTP.mjs'
export type { default as 'HXML' } from '../data/HXML.mjs'
export type { default as 'Hack' } from '../data/Hack.mjs'
export type { default as 'Haml' } from '../data/Haml.mjs'
export type { default as 'Handlebars' } from '../data/Handlebars.mjs'
export type { default as 'Harbour' } from '../data/Harbour.mjs'
export type { default as 'Hare' } from '../data/Hare.mjs'
export type { default as 'Haskell' } from '../data/Haskell.mjs'
export type { default as 'Haxe' } from '../data/Haxe.mjs'
export type { default as 'HiveQL' } from '../data/HiveQL.mjs'
export type { default as 'HolyC' } from '../data/HolyC.mjs'
export type { default as 'Hosts File' } from '../data/Hosts_20_File.mjs'
export type { default as 'Hy' } from '../data/Hy.mjs'
export type { default as 'HyPhy' } from '../data/HyPhy.mjs'
export type { default as 'IDL' } from '../data/IDL.mjs'
export type { default as 'IGOR Pro' } from '../data/IGOR_20_Pro.mjs'
export type { default as 'INI' } from '../data/INI.mjs'
export type { default as 'IRC log' } from '../data/IRC_20_log.mjs'
export type { default as 'ISPC' } from '../data/ISPC.mjs'
export type { default as 'Idris' } from '../data/Idris.mjs'
export type { default as 'Ignore List' } from '../data/Ignore_20_List.mjs'
export type { default as 'ImageJ Macro' } from '../data/ImageJ_20_Macro.mjs'
export type { default as 'Imba' } from '../data/Imba.mjs'
export type { default as 'Inform 7' } from '../data/Inform_20_7.mjs'
export type { default as 'Ink' } from '../data/Ink.mjs'
export type { default as 'Inno Setup' } from '../data/Inno_20_Setup.mjs'
export type { default as 'Io' } from '../data/Io.mjs'
export type { default as 'Ioke' } from '../data/Ioke.mjs'
export type { default as 'Isabelle' } from '../data/Isabelle.mjs'
export type { default as 'Isabelle ROOT' } from '../data/Isabelle_20_ROOT.mjs'
export type { default as 'J' } from '../data/J.mjs'
export type { default as 'JAR Manifest' } from '../data/JAR_20_Manifest.mjs'
export type { default as 'JCL' } from '../data/JCL.mjs'
export type { default as 'JFlex' } from '../data/JFlex.mjs'
export type { default as 'JSON' } from '../data/JSON.mjs'
export type { default as 'JSON with Comments' } from '../data/JSON_20_with_20_Comments.mjs'
export type { default as 'JSON5' } from '../data/JSON5.mjs'
export type { default as 'JSONLD' } from '../data/JSONLD.mjs'
export type { default as 'JSONiq' } from '../data/JSONiq.mjs'
export type { default as 'Jai' } from '../data/Jai.mjs'
export type { default as 'Janet' } from '../data/Janet.mjs'
export type { default as 'Jasmin' } from '../data/Jasmin.mjs'
export type { default as 'Java' } from '../data/Java.mjs'
export type { default as 'Java Properties' } from '../data/Java_20_Properties.mjs'
export type { default as 'Java Server Pages' } from '../data/Java_20_Server_20_Pages.mjs'
export type { default as 'Java Template Engine' } from '../data/Java_20_Template_20_Engine.mjs'
export type { default as 'JavaScript' } from '../data/JavaScript.mjs'
export type { default as 'JavaScript+ERB' } from '../data/JavaScript_2b_ERB.mjs'
export type { default as 'Jest Snapshot' } from '../data/Jest_20_Snapshot.mjs'
export type { default as 'JetBrains MPS' } from '../data/JetBrains_20_MPS.mjs'
export type { default as 'Jinja' } from '../data/Jinja.mjs'
export type { default as 'Jison' } from '../data/Jison.mjs'
export type { default as 'Jison Lex' } from '../data/Jison_20_Lex.mjs'
export type { default as 'Jolie' } from '../data/Jolie.mjs'
export type { default as 'Jsonnet' } from '../data/Jsonnet.mjs'
export type { default as 'Julia' } from '../data/Julia.mjs'
export type { default as 'Julia REPL' } from '../data/Julia_20_REPL.mjs'
export type { default as 'Jupyter Notebook' } from '../data/Jupyter_20_Notebook.mjs'
export type { default as 'Just' } from '../data/Just.mjs'
export type { default as 'KDL' } from '../data/KDL.mjs'
export type { default as 'KRL' } from '../data/KRL.mjs'
export type { default as 'Kaitai Struct' } from '../data/Kaitai_20_Struct.mjs'
export type { default as 'KakouneScript' } from '../data/KakouneScript.mjs'
export type { default as 'KerboScript' } from '../data/KerboScript.mjs'
export type { default as 'KiCad Layout' } from '../data/KiCad_20_Layout.mjs'
export type { default as 'KiCad Legacy Layout' } from '../data/KiCad_20_Legacy_20_Layout.mjs'
export type { default as 'KiCad Schematic' } from '../data/KiCad_20_Schematic.mjs'
export type { default as 'Kickstart' } from '../data/Kickstart.mjs'
export type { default as 'Kit' } from '../data/Kit.mjs'
export type { default as 'Koka' } from '../data/Koka.mjs'
export type { default as 'Kotlin' } from '../data/Kotlin.mjs'
export type { default as 'Kusto' } from '../data/Kusto.mjs'
export type { default as 'LFE' } from '../data/LFE.mjs'
export type { default as 'LLVM' } from '../data/LLVM.mjs'
export type { default as 'LOLCODE' } from '../data/LOLCODE.mjs'
export type { default as 'LSL' } from '../data/LSL.mjs'
export type { default as 'LTspice Symbol' } from '../data/LTspice_20_Symbol.mjs'
export type { default as 'LabVIEW' } from '../data/LabVIEW.mjs'
export type { default as 'Lark' } from '../data/Lark.mjs'
export type { default as 'Lasso' } from '../data/Lasso.mjs'
export type { default as 'Latte' } from '../data/Latte.mjs'
export type { default as 'Lean' } from '../data/Lean.mjs'
export type { default as 'Lean 4' } from '../data/Lean_20_4.mjs'
export type { default as 'Leo' } from '../data/Leo.mjs'
export type { default as 'Less' } from '../data/Less.mjs'
export type { default as 'Lex' } from '../data/Lex.mjs'
export type { default as 'LigoLANG' } from '../data/LigoLANG.mjs'
export type { default as 'LilyPond' } from '../data/LilyPond.mjs'
export type { default as 'Limbo' } from '../data/Limbo.mjs'
export type { default as 'Linear Programming' } from '../data/Linear_20_Programming.mjs'
export type { default as 'Linker Script' } from '../data/Linker_20_Script.mjs'
export type { default as 'Linux Kernel Module' } from '../data/Linux_20_Kernel_20_Module.mjs'
export type { default as 'Liquid' } from '../data/Liquid.mjs'
export type { default as 'Literate Agda' } from '../data/Literate_20_Agda.mjs'
export type { default as 'Literate CoffeeScript' } from '../data/Literate_20_CoffeeScript.mjs'
export type { default as 'Literate Haskell' } from '../data/Literate_20_Haskell.mjs'
export type { default as 'LiveCode Script' } from '../data/LiveCode_20_Script.mjs'
export type { default as 'LiveScript' } from '../data/LiveScript.mjs'
export type { default as 'Logos' } from '../data/Logos.mjs'
export type { default as 'Logtalk' } from '../data/Logtalk.mjs'
export type { default as 'LookML' } from '../data/LookML.mjs'
export type { default as 'LoomScript' } from '../data/LoomScript.mjs'
export type { default as 'Lua' } from '../data/Lua.mjs'
export type { default as 'Luau' } from '../data/Luau.mjs'
export type { default as 'M' } from '../data/M.mjs'
export type { default as 'M3U' } from '../data/M3U.mjs'
export type { default as 'M4' } from '../data/M4.mjs'
export type { default as 'M4Sugar' } from '../data/M4Sugar.mjs'
export type { default as 'MATLAB' } from '../data/MATLAB.mjs'
export type { default as 'MAXScript' } from '../data/MAXScript.mjs'
export type { default as 'MDX' } from '../data/MDX.mjs'
export type { default as 'MLIR' } from '../data/MLIR.mjs'
export type { default as 'MQL4' } from '../data/MQL4.mjs'
export type { default as 'MQL5' } from '../data/MQL5.mjs'
export type { default as 'MTML' } from '../data/MTML.mjs'
export type { default as 'MUF' } from '../data/MUF.mjs'
export type { default as 'Macaulay2' } from '../data/Macaulay2.mjs'
export type { default as 'Makefile' } from '../data/Makefile.mjs'
export type { default as 'Mako' } from '../data/Mako.mjs'
export type { default as 'Markdown' } from '../data/Markdown.mjs'
export type { default as 'Marko' } from '../data/Marko.mjs'
export type { default as 'Mask' } from '../data/Mask.mjs'
export type { default as 'Mathematica' } from '../data/Mathematica.mjs'
export type { default as 'Maven POM' } from '../data/Maven_20_POM.mjs'
export type { default as 'Max' } from '../data/Max.mjs'
export type { default as 'Mercury' } from '../data/Mercury.mjs'
export type { default as 'Mermaid' } from '../data/Mermaid.mjs'
export type { default as 'Meson' } from '../data/Meson.mjs'
export type { default as 'Metal' } from '../data/Metal.mjs'
export type { default as 'Microsoft Developer Studio Project' } from '../data/Microsoft_20_Developer_20_Studio_20_Project.mjs'
export type { default as 'Microsoft Visual Studio Solution' } from '../data/Microsoft_20_Visual_20_Studio_20_Solution.mjs'
export type { default as 'MiniD' } from '../data/MiniD.mjs'
export type { default as 'MiniYAML' } from '../data/MiniYAML.mjs'
export type { default as 'MiniZinc' } from '../data/MiniZinc.mjs'
export type { default as 'MiniZinc Data' } from '../data/MiniZinc_20_Data.mjs'
export type { default as 'Mint' } from '../data/Mint.mjs'
export type { default as 'Mirah' } from '../data/Mirah.mjs'
export type { default as 'Modelica' } from '../data/Modelica.mjs'
export type { default as 'Modula-2' } from '../data/Modula-2.mjs'
export type { default as 'Modula-3' } from '../data/Modula-3.mjs'
export type { default as 'Module Management System' } from '../data/Module_20_Management_20_System.mjs'
export type { default as 'Mojo' } from '../data/Mojo.mjs'
export type { default as 'Monkey' } from '../data/Monkey.mjs'
export type { default as 'Monkey C' } from '../data/Monkey_20_C.mjs'
export type { default as 'Moocode' } from '../data/Moocode.mjs'
export type { default as 'MoonBit' } from '../data/MoonBit.mjs'
export type { default as 'MoonScript' } from '../data/MoonScript.mjs'
export type { default as 'Motoko' } from '../data/Motoko.mjs'
export type { default as 'Motorola 68K Assembly' } from '../data/Motorola_20_68K_20_Assembly.mjs'
export type { default as 'Move' } from '../data/Move.mjs'
export type { default as 'Muse' } from '../data/Muse.mjs'
export type { default as 'Mustache' } from '../data/Mustache.mjs'
export type { default as 'Myghty' } from '../data/Myghty.mjs'
export type { default as 'NASL' } from '../data/NASL.mjs'
export type { default as 'NCL' } from '../data/NCL.mjs'
export type { default as 'NEON' } from '../data/NEON.mjs'
export type { default as 'NL' } from '../data/NL.mjs'
export type { default as 'NMODL' } from '../data/NMODL.mjs'
export type { default as 'NPM Config' } from '../data/NPM_20_Config.mjs'
export type { default as 'NSIS' } from '../data/NSIS.mjs'
export type { default as 'NWScript' } from '../data/NWScript.mjs'
export type { default as 'Nasal' } from '../data/Nasal.mjs'
export type { default as 'Nearley' } from '../data/Nearley.mjs'
export type { default as 'Nemerle' } from '../data/Nemerle.mjs'
export type { default as 'NetLinx' } from '../data/NetLinx.mjs'
export type { default as 'NetLinx+ERB' } from '../data/NetLinx_2b_ERB.mjs'
export type { default as 'NetLogo' } from '../data/NetLogo.mjs'
export type { default as 'NewLisp' } from '../data/NewLisp.mjs'
export type { default as 'Nextflow' } from '../data/Nextflow.mjs'
export type { default as 'Nginx' } from '../data/Nginx.mjs'
export type { default as 'Nim' } from '../data/Nim.mjs'
export type { default as 'Ninja' } from '../data/Ninja.mjs'
export type { default as 'Nit' } from '../data/Nit.mjs'
export type { default as 'Nix' } from '../data/Nix.mjs'
export type { default as 'Noir' } from '../data/Noir.mjs'
export type { default as 'Nu' } from '../data/Nu.mjs'
export type { default as 'NumPy' } from '../data/NumPy.mjs'
export type { default as 'Nunjucks' } from '../data/Nunjucks.mjs'
export type { default as 'Nushell' } from '../data/Nushell.mjs'
export type { default as 'OASv2-json' } from '../data/OASv2-json.mjs'
export type { default as 'OASv2-yaml' } from '../data/OASv2-yaml.mjs'
export type { default as 'OASv3-json' } from '../data/OASv3-json.mjs'
export type { default as 'OASv3-yaml' } from '../data/OASv3-yaml.mjs'
export type { default as 'OCaml' } from '../data/OCaml.mjs'
export type { default as 'OMNeT++ MSG' } from '../data/OMNeT_2b__2b__20_MSG.mjs'
export type { default as 'OMNeT++ NED' } from '../data/OMNeT_2b__2b__20_NED.mjs'
export type { default as 'Oberon' } from '../data/Oberon.mjs'
export type { default as 'ObjDump' } from '../data/ObjDump.mjs'
export type { default as 'Object Data Instance Notation' } from '../data/Object_20_Data_20_Instance_20_Notation.mjs'
export type { default as 'ObjectScript' } from '../data/ObjectScript.mjs'
export type { default as 'Objective-C' } from '../data/Objective-C.mjs'
export type { default as 'Objective-C++' } from '../data/Objective-C_2b__2b_.mjs'
export type { default as 'Objective-J' } from '../data/Objective-J.mjs'
export type { default as 'Odin' } from '../data/Odin.mjs'
export type { default as 'Omgrofl' } from '../data/Omgrofl.mjs'
export type { default as 'Opa' } from '../data/Opa.mjs'
export type { default as 'Opal' } from '../data/Opal.mjs'
export type { default as 'Open Policy Agent' } from '../data/Open_20_Policy_20_Agent.mjs'
export type { default as 'OpenAPI Specification v2' } from '../data/OpenAPI_20_Specification_20_v2.mjs'
export type { default as 'OpenAPI Specification v3' } from '../data/OpenAPI_20_Specification_20_v3.mjs'
export type { default as 'OpenCL' } from '../data/OpenCL.mjs'
export type { default as 'OpenEdge ABL' } from '../data/OpenEdge_20_ABL.mjs'
export type { default as 'OpenQASM' } from '../data/OpenQASM.mjs'
export type { default as 'OpenRC runscript' } from '../data/OpenRC_20_runscript.mjs'
export type { default as 'OpenSCAD' } from '../data/OpenSCAD.mjs'
export type { default as 'OpenStep Property List' } from '../data/OpenStep_20_Property_20_List.mjs'
export type { default as 'OpenType Feature File' } from '../data/OpenType_20_Feature_20_File.mjs'
export type { default as 'Option List' } from '../data/Option_20_List.mjs'
export type { default as 'Org' } from '../data/Org.mjs'
export type { default as 'OverpassQL' } from '../data/OverpassQL.mjs'
export type { default as 'Ox' } from '../data/Ox.mjs'
export type { default as 'Oxygene' } from '../data/Oxygene.mjs'
export type { default as 'Oz' } from '../data/Oz.mjs'
export type { default as 'P4' } from '../data/P4.mjs'
export type { default as 'PDDL' } from '../data/PDDL.mjs'
export type { default as 'PEG.js' } from '../data/PEG.js.mjs'
export type { default as 'PHP' } from '../data/PHP.mjs'
export type { default as 'PLSQL' } from '../data/PLSQL.mjs'
export type { default as 'PLpgSQL' } from '../data/PLpgSQL.mjs'
export type { default as 'POV-Ray SDL' } from '../data/POV-Ray_20_SDL.mjs'
export type { default as 'Pact' } from '../data/Pact.mjs'
export type { default as 'Pan' } from '../data/Pan.mjs'
export type { default as 'Papyrus' } from '../data/Papyrus.mjs'
export type { default as 'Parrot' } from '../data/Parrot.mjs'
export type { default as 'Parrot Assembly' } from '../data/Parrot_20_Assembly.mjs'
export type { default as 'Parrot Internal Representation' } from '../data/Parrot_20_Internal_20_Representation.mjs'
export type { default as 'Pascal' } from '../data/Pascal.mjs'
export type { default as 'Pawn' } from '../data/Pawn.mjs'
export type { default as 'Pep8' } from '../data/Pep8.mjs'
export type { default as 'Perl' } from '../data/Perl.mjs'
export type { default as 'Pic' } from '../data/Pic.mjs'
export type { default as 'Pickle' } from '../data/Pickle.mjs'
export type { default as 'PicoLisp' } from '../data/PicoLisp.mjs'
export type { default as 'PigLatin' } from '../data/PigLatin.mjs'
export type { default as 'Pike' } from '../data/Pike.mjs'
export type { default as 'Pip Requirements' } from '../data/Pip_20_Requirements.mjs'
export type { default as 'Pkl' } from '../data/Pkl.mjs'
export type { default as 'PlantUML' } from '../data/PlantUML.mjs'
export type { default as 'Pod' } from '../data/Pod.mjs'
export type { default as 'Pod 6' } from '../data/Pod_20_6.mjs'
export type { default as 'PogoScript' } from '../data/PogoScript.mjs'
export type { default as 'Polar' } from '../data/Polar.mjs'
export type { default as 'Pony' } from '../data/Pony.mjs'
export type { default as 'Portugol' } from '../data/Portugol.mjs'
export type { default as 'PostCSS' } from '../data/PostCSS.mjs'
export type { default as 'PostScript' } from '../data/PostScript.mjs'
export type { default as 'PowerBuilder' } from '../data/PowerBuilder.mjs'
export type { default as 'PowerShell' } from '../data/PowerShell.mjs'
export type { default as 'Praat' } from '../data/Praat.mjs'
export type { default as 'Prisma' } from '../data/Prisma.mjs'
export type { default as 'Processing' } from '../data/Processing.mjs'
export type { default as 'Procfile' } from '../data/Procfile.mjs'
export type { default as 'Proguard' } from '../data/Proguard.mjs'
export type { default as 'Prolog' } from '../data/Prolog.mjs'
export type { default as 'Promela' } from '../data/Promela.mjs'
export type { default as 'Propeller Spin' } from '../data/Propeller_20_Spin.mjs'
export type { default as 'Protocol Buffer' } from '../data/Protocol_20_Buffer.mjs'
export type { default as 'Protocol Buffer Text Format' } from '../data/Protocol_20_Buffer_20_Text_20_Format.mjs'
export type { default as 'Public Key' } from '../data/Public_20_Key.mjs'
export type { default as 'Pug' } from '../data/Pug.mjs'
export type { default as 'Puppet' } from '../data/Puppet.mjs'
export type { default as 'Pure Data' } from '../data/Pure_20_Data.mjs'
export type { default as 'PureBasic' } from '../data/PureBasic.mjs'
export type { default as 'PureScript' } from '../data/PureScript.mjs'
export type { default as 'Pyret' } from '../data/Pyret.mjs'
export type { default as 'Python' } from '../data/Python.mjs'
export type { default as 'Python console' } from '../data/Python_20_console.mjs'
export type { default as 'Python traceback' } from '../data/Python_20_traceback.mjs'
export type { default as 'Q#' } from '../data/Q_23_.mjs'
export type { default as 'QML' } from '../data/QML.mjs'
export type { default as 'QMake' } from '../data/QMake.mjs'
export type { default as 'Qt Script' } from '../data/Qt_20_Script.mjs'
export type { default as 'Quake' } from '../data/Quake.mjs'
export type { default as 'QuickBASIC' } from '../data/QuickBASIC.mjs'
export type { default as 'R' } from '../data/R.mjs'
export type { default as 'RAML' } from '../data/RAML.mjs'
export type { default as 'RBS' } from '../data/RBS.mjs'
export type { default as 'RDoc' } from '../data/RDoc.mjs'
export type { default as 'REALbasic' } from '../data/REALbasic.mjs'
export type { default as 'REXX' } from '../data/REXX.mjs'
export type { default as 'RMarkdown' } from '../data/RMarkdown.mjs'
export type { default as 'RON' } from '../data/RON.mjs'
export type { default as 'RPC' } from '../data/RPC.mjs'
export type { default as 'RPGLE' } from '../data/RPGLE.mjs'
export type { default as 'RPM Spec' } from '../data/RPM_20_Spec.mjs'
export type { default as 'RUNOFF' } from '../data/RUNOFF.mjs'
export type { default as 'Racket' } from '../data/Racket.mjs'
export type { default as 'Ragel' } from '../data/Ragel.mjs'
export type { default as 'Raku' } from '../data/Raku.mjs'
export type { default as 'Rascal' } from '../data/Rascal.mjs'
export type { default as 'Raw token data' } from '../data/Raw_20_token_20_data.mjs'
export type { default as 'ReScript' } from '../data/ReScript.mjs'
export type { default as 'Readline Config' } from '../data/Readline_20_Config.mjs'
export type { default as 'Reason' } from '../data/Reason.mjs'
export type { default as 'ReasonLIGO' } from '../data/ReasonLIGO.mjs'
export type { default as 'Rebol' } from '../data/Rebol.mjs'
export type { default as 'Record Jar' } from '../data/Record_20_Jar.mjs'
export type { default as 'Red' } from '../data/Red.mjs'
export type { default as 'Redcode' } from '../data/Redcode.mjs'
export type { default as 'Redirect Rules' } from '../data/Redirect_20_Rules.mjs'
export type { default as 'Regular Expression' } from '../data/Regular_20_Expression.mjs'
export type { default as "Ren'Py" } from '../data/Ren_27_Py.mjs'
export type { default as 'RenderScript' } from '../data/RenderScript.mjs'
export type { default as 'Rez' } from '../data/Rez.mjs'
export type { default as 'Rich Text Format' } from '../data/Rich_20_Text_20_Format.mjs'
export type { default as 'Ring' } from '../data/Ring.mjs'
export type { default as 'Riot' } from '../data/Riot.mjs'
export type { default as 'RobotFramework' } from '../data/RobotFramework.mjs'
export type { default as 'Roc' } from '../data/Roc.mjs'
export type { default as 'Rocq Prover' } from '../data/Rocq_20_Prover.mjs'
export type { default as 'Roff' } from '../data/Roff.mjs'
export type { default as 'Roff Manpage' } from '../data/Roff_20_Manpage.mjs'
export type { default as 'Rouge' } from '../data/Rouge.mjs'
export type { default as 'RouterOS Script' } from '../data/RouterOS_20_Script.mjs'
export type { default as 'Ruby' } from '../data/Ruby.mjs'
export type { default as 'Rust' } from '../data/Rust.mjs'
export type { default as 'SAS' } from '../data/SAS.mjs'
export type { default as 'SCSS' } from '../data/SCSS.mjs'
export type { default as 'SELinux Policy' } from '../data/SELinux_20_Policy.mjs'
export type { default as 'SMT' } from '../data/SMT.mjs'
export type { default as 'SPARQL' } from '../data/SPARQL.mjs'
export type { default as 'SQF' } from '../data/SQF.mjs'
export type { default as 'SQL' } from '../data/SQL.mjs'
export type { default as 'SQLPL' } from '../data/SQLPL.mjs'
export type { default as 'SRecode Template' } from '../data/SRecode_20_Template.mjs'
export type { default as 'SSH Config' } from '../data/SSH_20_Config.mjs'
export type { default as 'STAR' } from '../data/STAR.mjs'
export type { default as 'STL' } from '../data/STL.mjs'
export type { default as 'STON' } from '../data/STON.mjs'
export type { default as 'SVG' } from '../data/SVG.mjs'
export type { default as 'SWIG' } from '../data/SWIG.mjs'
export type { default as 'Sage' } from '../data/Sage.mjs'
export type { default as 'Sail' } from '../data/Sail.mjs'
export type { default as 'SaltStack' } from '../data/SaltStack.mjs'
export type { default as 'Sass' } from '../data/Sass.mjs'
export type { default as 'Scala' } from '../data/Scala.mjs'
export type { default as 'Scaml' } from '../data/Scaml.mjs'
export type { default as 'Scenic' } from '../data/Scenic.mjs'
export type { default as 'Scheme' } from '../data/Scheme.mjs'
export type { default as 'Scilab' } from '../data/Scilab.mjs'
export type { default as 'Self' } from '../data/Self.mjs'
export type { default as 'ShaderLab' } from '../data/ShaderLab.mjs'
export type { default as 'Shell' } from '../data/Shell.mjs'
export type { default as 'ShellCheck Config' } from '../data/ShellCheck_20_Config.mjs'
export type { default as 'ShellSession' } from '../data/ShellSession.mjs'
export type { default as 'Shen' } from '../data/Shen.mjs'
export type { default as 'Sieve' } from '../data/Sieve.mjs'
export type { default as 'Simple File Verification' } from '../data/Simple_20_File_20_Verification.mjs'
export type { default as 'Singularity' } from '../data/Singularity.mjs'
export type { default as 'Slang' } from '../data/Slang.mjs'
export type { default as 'Slash' } from '../data/Slash.mjs'
export type { default as 'Slice' } from '../data/Slice.mjs'
export type { default as 'Slim' } from '../data/Slim.mjs'
export type { default as 'Slint' } from '../data/Slint.mjs'
export type { default as 'SmPL' } from '../data/SmPL.mjs'
export type { default as 'Smali' } from '../data/Smali.mjs'
export type { default as 'Smalltalk' } from '../data/Smalltalk.mjs'
export type { default as 'Smarty' } from '../data/Smarty.mjs'
export type { default as 'Smithy' } from '../data/Smithy.mjs'
export type { default as 'Snakemake' } from '../data/Snakemake.mjs'
export type { default as 'Solidity' } from '../data/Solidity.mjs'
export type { default as 'Soong' } from '../data/Soong.mjs'
export type { default as 'SourcePawn' } from '../data/SourcePawn.mjs'
export type { default as 'Spline Font Database' } from '../data/Spline_20_Font_20_Database.mjs'
export type { default as 'Squirrel' } from '../data/Squirrel.mjs'
export type { default as 'Stan' } from '../data/Stan.mjs'
export type { default as 'Standard ML' } from '../data/Standard_20_ML.mjs'
export type { default as 'Starlark' } from '../data/Starlark.mjs'
export type { default as 'Stata' } from '../data/Stata.mjs'
export type { default as 'StringTemplate' } from '../data/StringTemplate.mjs'
export type { default as 'Stylus' } from '../data/Stylus.mjs'
export type { default as 'SubRip Text' } from '../data/SubRip_20_Text.mjs'
export type { default as 'SugarSS' } from '../data/SugarSS.mjs'
export type { default as 'SuperCollider' } from '../data/SuperCollider.mjs'
export type { default as 'Survex data' } from '../data/Survex_20_data.mjs'
export type { default as 'Svelte' } from '../data/Svelte.mjs'
export type { default as 'Sway' } from '../data/Sway.mjs'
export type { default as 'Sweave' } from '../data/Sweave.mjs'
export type { default as 'Swift' } from '../data/Swift.mjs'
export type { default as 'SystemVerilog' } from '../data/SystemVerilog.mjs'
export type { default as 'TI Program' } from '../data/TI_20_Program.mjs'
export type { default as 'TL-Verilog' } from '../data/TL-Verilog.mjs'
export type { default as 'TLA' } from '../data/TLA.mjs'
export type { default as 'TOML' } from '../data/TOML.mjs'
export type { default as 'TSPLIB data' } from '../data/TSPLIB_20_data.mjs'
export type { default as 'TSQL' } from '../data/TSQL.mjs'
export type { default as 'TSV' } from '../data/TSV.mjs'
export type { default as 'TSX' } from '../data/TSX.mjs'
export type { default as 'TXL' } from '../data/TXL.mjs'
export type { default as 'Tact' } from '../data/Tact.mjs'
export type { default as 'Talon' } from '../data/Talon.mjs'
export type { default as 'Tcl' } from '../data/Tcl.mjs'
export type { default as 'Tcsh' } from '../data/Tcsh.mjs'
export type { default as 'TeX' } from '../data/TeX.mjs'
export type { default as 'Tea' } from '../data/Tea.mjs'
export type { default as 'Terra' } from '../data/Terra.mjs'
export type { default as 'Terraform Template' } from '../data/Terraform_20_Template.mjs'
export type { default as 'Texinfo' } from '../data/Texinfo.mjs'
export type { default as 'Text' } from '../data/Text.mjs'
export type { default as 'TextGrid' } from '../data/TextGrid.mjs'
export type { default as 'TextMate Properties' } from '../data/TextMate_20_Properties.mjs'
export type { default as 'Textile' } from '../data/Textile.mjs'
export type { default as 'Thrift' } from '../data/Thrift.mjs'
export type { default as 'Toit' } from '../data/Toit.mjs'
export type { default as 'Tor Config' } from '../data/Tor_20_Config.mjs'
export type { default as 'Tree-sitter Query' } from '../data/Tree-sitter_20_Query.mjs'
export type { default as 'Turing' } from '../data/Turing.mjs'
export type { default as 'Turtle' } from '../data/Turtle.mjs'
export type { default as 'Twig' } from '../data/Twig.mjs'
export type { default as 'Type Language' } from '../data/Type_20_Language.mjs'
export type { default as 'TypeScript' } from '../data/TypeScript.mjs'
export type { default as 'TypeSpec' } from '../data/TypeSpec.mjs'
export type { default as 'Typst' } from '../data/Typst.mjs'
export type { default as 'Unified Parallel C' } from '../data/Unified_20_Parallel_20_C.mjs'
export type { default as 'Unity3D Asset' } from '../data/Unity3D_20_Asset.mjs'
export type { default as 'Unix Assembly' } from '../data/Unix_20_Assembly.mjs'
export type { default as 'Uno' } from '../data/Uno.mjs'
export type { default as 'UnrealScript' } from '../data/UnrealScript.mjs'
export type { default as 'Untyped Plutus Core' } from '../data/Untyped_20_Plutus_20_Core.mjs'
export type { default as 'UrWeb' } from '../data/UrWeb.mjs'
export type { default as 'V' } from '../data/V.mjs'
export type { default as 'VBA' } from '../data/VBA.mjs'
export type { default as 'VBScript' } from '../data/VBScript.mjs'
export type { default as 'VCL' } from '../data/VCL.mjs'
export type { default as 'VHDL' } from '../data/VHDL.mjs'
export type { default as 'Vala' } from '../data/Vala.mjs'
export type { default as 'Valve Data Format' } from '../data/Valve_20_Data_20_Format.mjs'
export type { default as 'Velocity Template Language' } from '../data/Velocity_20_Template_20_Language.mjs'
export type { default as 'Vento' } from '../data/Vento.mjs'
export type { default as 'Verilog' } from '../data/Verilog.mjs'
export type { default as 'Vim Help File' } from '../data/Vim_20_Help_20_File.mjs'
export type { default as 'Vim Script' } from '../data/Vim_20_Script.mjs'
export type { default as 'Vim Snippet' } from '../data/Vim_20_Snippet.mjs'
export type { default as 'Visual Basic .NET' } from '../data/Visual_20_Basic_20_.NET.mjs'
export type { default as 'Visual Basic 6.0' } from '../data/Visual_20_Basic_20_6.0.mjs'
export type { default as 'Volt' } from '../data/Volt.mjs'
export type { default as 'Vue' } from '../data/Vue.mjs'
export type { default as 'Vyper' } from '../data/Vyper.mjs'
export type { default as 'WDL' } from '../data/WDL.mjs'
export type { default as 'WGSL' } from '../data/WGSL.mjs'
export type { default as 'Wavefront Material' } from '../data/Wavefront_20_Material.mjs'
export type { default as 'Wavefront Object' } from '../data/Wavefront_20_Object.mjs'
export type { default as 'Web Ontology Language' } from '../data/Web_20_Ontology_20_Language.mjs'
export type { default as 'WebAssembly' } from '../data/WebAssembly.mjs'
export type { default as 'WebAssembly Interface Type' } from '../data/WebAssembly_20_Interface_20_Type.mjs'
export type { default as 'WebIDL' } from '../data/WebIDL.mjs'
export type { default as 'WebVTT' } from '../data/WebVTT.mjs'
export type { default as 'Wget Config' } from '../data/Wget_20_Config.mjs'
export type { default as 'Whiley' } from '../data/Whiley.mjs'
export type { default as 'Wikitext' } from '../data/Wikitext.mjs'
export type { default as 'Win32 Message File' } from '../data/Win32_20_Message_20_File.mjs'
export type { default as 'Windows Registry Entries' } from '../data/Windows_20_Registry_20_Entries.mjs'
export type { default as 'Witcher Script' } from '../data/Witcher_20_Script.mjs'
export type { default as 'Wollok' } from '../data/Wollok.mjs'
export type { default as 'World of Warcraft Addon Data' } from '../data/World_20_of_20_Warcraft_20_Addon_20_Data.mjs'
export type { default as 'Wren' } from '../data/Wren.mjs'
export type { default as 'X BitMap' } from '../data/X_20_BitMap.mjs'
export type { default as 'X Font Directory Index' } from '../data/X_20_Font_20_Directory_20_Index.mjs'
export type { default as 'X PixMap' } from '../data/X_20_PixMap.mjs'
export type { default as 'X10' } from '../data/X10.mjs'
export type { default as 'XC' } from '../data/XC.mjs'
export type { default as 'XCompose' } from '../data/XCompose.mjs'
export type { default as 'XML' } from '../data/XML.mjs'
export type { default as 'XML Property List' } from '../data/XML_20_Property_20_List.mjs'
export type { default as 'XPages' } from '../data/XPages.mjs'
export type { default as 'XProc' } from '../data/XProc.mjs'
export type { default as 'XQuery' } from '../data/XQuery.mjs'
export type { default as 'XS' } from '../data/XS.mjs'
export type { default as 'XSLT' } from '../data/XSLT.mjs'
export type { default as 'Xmake' } from '../data/Xmake.mjs'
export type { default as 'Xojo' } from '../data/Xojo.mjs'
export type { default as 'Xonsh' } from '../data/Xonsh.mjs'
export type { default as 'Xtend' } from '../data/Xtend.mjs'
export type { default as 'YAML' } from '../data/YAML.mjs'
export type { default as 'YANG' } from '../data/YANG.mjs'
export type { default as 'YARA' } from '../data/YARA.mjs'
export type { default as 'YASnippet' } from '../data/YASnippet.mjs'
export type { default as 'Yacc' } from '../data/Yacc.mjs'
export type { default as 'Yul' } from '../data/Yul.mjs'
export type { default as 'ZAP' } from '../data/ZAP.mjs'
export type { default as 'ZIL' } from '../data/ZIL.mjs'
export type { default as 'Zeek' } from '../data/Zeek.mjs'
export type { default as 'ZenScript' } from '../data/ZenScript.mjs'
export type { default as 'Zephir' } from '../data/Zephir.mjs'
export type { default as 'Zig' } from '../data/Zig.mjs'
export type { default as 'Zimpl' } from '../data/Zimpl.mjs'
export type { default as 'Zmodel' } from '../data/Zmodel.mjs'
export type { default as 'cURL Config' } from '../data/cURL_20_Config.mjs'
export type { default as 'crontab' } from '../data/crontab.mjs'
export type { default as 'desktop' } from '../data/desktop.mjs'
export type { default as 'dircolors' } from '../data/dircolors.mjs'
export type { default as 'eC' } from '../data/eC.mjs'
export type { default as 'edn' } from '../data/edn.mjs'
export type { default as 'fish' } from '../data/fish.mjs'
export type { default as 'hoon' } from '../data/hoon.mjs'
export type { default as 'iCalendar' } from '../data/iCalendar.mjs'
export type { default as 'jq' } from '../data/jq.mjs'
export type { default as 'kvlang' } from '../data/kvlang.mjs'
export type { default as 'mIRC Script' } from '../data/mIRC_20_Script.mjs'
export type { default as 'mcfunction' } from '../data/mcfunction.mjs'
export type { default as 'mdsvex' } from '../data/mdsvex.mjs'
export type { default as 'mupad' } from '../data/mupad.mjs'
export type { default as 'nanorc' } from '../data/nanorc.mjs'
export type { default as 'nesC' } from '../data/nesC.mjs'
export type { default as 'ooc' } from '../data/ooc.mjs'
export type { default as 'q' } from '../data/q.mjs'
export type { default as 'reStructuredText' } from '../data/reStructuredText.mjs'
export type { default as 'robots.txt' } from '../data/robots.txt.mjs'
export type { default as 'sed' } from '../data/sed.mjs'
export type { default as 'templ' } from '../data/templ.mjs'
export type { default as 'vCard' } from '../data/vCard.mjs'
export type { default as 'wisp' } from '../data/wisp.mjs'
export type { default as 'xBase' } from '../data/xBase.mjs'
