on:
  workflow_call:
    inputs:
      command:
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '10'
          cache: yarn
      - run: yarn
      - run: ${{ inputs.command }}
