on:
  - push
  - pull_request

jobs:
  lint:
    uses: ./.github/workflows/_shared.yml
    with:
      command: pnpm run lint
  check:
    uses: ./.github/workflows/_shared.yml
    with:
      command: pnpm run check
  build:
    uses: ./.github/workflows/_shared.yml
    with:
      command: pnpm run build
  test:
    uses: ./.github/workflows/_shared.yml
    with:
      command: pnpm run test
